import type {
  Crisis,
  Donation,
  Provider,
  Beneficiary,
  User,
  FraudAlert,
  BlacklistEntry,
  DistributionProof,
} from "@/types"

// Mock Bangladesh divisions
const DIVISIONS = ["Dhaka", "Chittagong", "Sylhet", "Khulna", "Rajshahi", "Barisal", "Rangpur", "Mymensingh"]
const DISTRICTS_BY_DIVISION: Record<string, string[]> = {
  Dhaka: ["Dhaka", "Gazipur", "Narayanganj", "Manikganj", "Munshiganj", "Tangail", "Faridpur", "Rajbari"],
  Sylhet: ["Sylhet", "Sunamganj", "Moulvibazar", "Habiganj"],
  Khulna: ["Khulna", "Satkhira", "Bagerhat", "Jhenaidah", "Magura", "Narail"],
  Chittagong: ["Chattogram", "Cox's Bazar", "Rangamati", "Khagrachari", "Noakhali", "Feni", "Lakshmipur"],
  Rajshahi: ["Rajshahi", "Natore", "Naogaon", "Chapainawabganj", "Pabna", "Bogura"],
  Barisal: ["Barisal", "Patuakhali", "Pirojpur", "Jhalokati", "Bhola"],
  Rangpur: ["Rangpur", "Dinajpur", "Thakurgaon", "Panchagarh", "Lalmonirhat", "Kurigram", "Gaibandha"],
  Mymensingh: ["Mymensingh", "Jamalpur", "Sherpur", "Netrokona"],
}

// Mock Donors
export const mockDonors: User[] = [
  {
    id: "donor-1",
    role: "donor",
    name: "Rashed Ahmed",
    email: "rashed@example.com",
    phone: "+88017XXXXXXXX",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=rashed",
    verified: true,
    createdAt: "2024-01-15",
  },
  {
    id: "donor-2",
    role: "donor",
    name: "Fatima Rahman",
    email: "fatima@example.com",
    phone: "+88018XXXXXXXX",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=fatima",
    verified: true,
    createdAt: "2024-02-20",
  },
  {
    id: "donor-3",
    role: "donor",
    name: "Karim Hassan",
    email: "karim@example.com",
    phone: "+88019XXXXXXXX",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=karim",
    verified: true,
    createdAt: "2024-03-10",
  },
  {
    id: "donor-4",
    role: "donor",
    name: "Sara Chowdhury",
    email: "sara@example.com",
    phone: "+88016XXXXXXXX",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=sara",
    verified: true,
    createdAt: "2024-04-05",
  },
  {
    id: "donor-5",
    role: "donor",
    name: "Imran Khan",
    email: "imran@example.com",
    phone: "+88015XXXXXXXX",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=imran",
    verified: true,
    createdAt: "2024-05-12",
  },
]

// Mock Crises
export const mockCrises: Crisis[] = [
  {
    id: "crisis-1",
    title: "Sylhet Monsoon Flooding 2024",
    description:
      "Heavy monsoon rains have caused severe flooding affecting over 50,000 people. Emergency shelter and food supplies urgently needed.",
    type: "flood",
    location: {
      division: "Sylhet",
      district: "Sylhet",
      upazila: "Sylhet Sadar",
      coordinates: { lat: 24.8949, lng: 91.8687 },
    },
    severity: 92,
    affectedPopulation: 48500,
    fundingNeeded: 5000000,
    fundingReceived: 3250000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: ["https://example.com/news/sylhet-flood"],
    satelliteData: "NASA satellite confirms 15% area inundation",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-15",
    trending: true,
    upvotes: 456,
    downvotes: 12,
  },
  {
    id: "crisis-2",
    title: "Satkhira Cyclone Recovery",
    description: "Recent cyclone destroyed 2000+ homes. Rebuilding materials and temporary shelter urgently needed.",
    type: "flood",
    location: {
      division: "Khulna",
      district: "Satkhira",
      upazila: "Satkhira Sadar",
      coordinates: { lat: 22.348, lng: 89.078 },
    },
    severity: 85,
    affectedPopulation: 32000,
    fundingNeeded: 3200000,
    fundingReceived: 1850000,
    status: "active",
    verified: true,
    verificationStatus: "community-validated",
    evidenceImages: ["/cyclone-damage-homes.jpg"],
    newsLinks: ["https://example.com/news/satkhira-cyclone"],
    createdAt: "2024-05-20",
    updatedAt: "2024-06-10",
    trending: true,
    upvotes: 234,
    downvotes: 8,
  },
  {
    id: "crisis-3",
    title: "Medical Emergency Response - Cancer Ward",
    description: "Underprivileged cancer patients need treatment fees. Emergency medical fund established.",
    type: "medical",
    location: {
      division: "Dhaka",
      district: "Dhaka",
      upazila: "Dhaka Sadar",
      coordinates: { lat: 23.8103, lng: 90.4125 },
    },
    severity: 78,
    affectedPopulation: 250,
    fundingNeeded: 1500000,
    fundingReceived: 920000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/medical-facility.jpg"],
    newsLinks: [],
    createdAt: "2024-06-05",
    updatedAt: "2024-06-12",
    trending: false,
    upvotes: 189,
    downvotes: 3,
  },
  {
    id: "crisis-4",
    title: "Back-to-School Fund for Underprivileged",
    description: "5000 students unable to afford school materials. Education is the key to breaking poverty cycles.",
    type: "education",
    location: {
      division: "Rangpur",
      district: "Dinajpur",
      upazila: "Dinajpur Sadar",
      coordinates: { lat: 25.6358, lng: 88.6441 },
    },
    severity: 62,
    affectedPopulation: 5000,
    fundingNeeded: 2000000,
    fundingReceived: 1200000,
    status: "active",
    verified: true,
    verificationStatus: "under-review",
    evidenceImages: ["/school-students-classroom.jpg"],
    newsLinks: [],
    createdAt: "2024-06-08",
    updatedAt: "2024-06-13",
    trending: false,
    upvotes: 167,
    downvotes: 5,
  },
  {
    id: "crisis-5",
    title: "Winter Poverty Crisis - Vulnerable Families",
    description:
      "Winter approaching. 10,000 families without proper clothing and blankets. Temperature drops below 5°C.",
    type: "poverty",
    location: {
      division: "Mymensingh",
      district: "Mymensingh",
      upazila: "Mymensingh Sadar",
      coordinates: { lat: 24.7471, lng: 90.4203 },
    },
    severity: 74,
    affectedPopulation: 10000,
    fundingNeeded: 2500000,
    fundingReceived: 800000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/winter-poverty-families.jpg"],
    newsLinks: [],
    createdAt: "2024-11-01",
    updatedAt: "2024-11-05",
    trending: true,
    upvotes: 298,
    downvotes: 6,
  },
  {
    id: "crisis-6",
    title: "Dhaka Slum Fire Emergency",
    description: "Major fire destroyed 500 shanties in Korail slum. 2000+ people homeless, need immediate shelter.",
    type: "fire",
    location: {
      division: "Dhaka",
      district: "Dhaka",
      upazila: "Gulshan",
      coordinates: { lat: 23.7925, lng: 90.4078 },
    },
    severity: 95,
    affectedPopulation: 2000,
    fundingNeeded: 4000000,
    fundingReceived: 1500000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: ["https://example.com/news/dhaka-fire"],
    satelliteData: "Thermal imaging confirms extensive damage",
    createdAt: "2024-06-14",
    updatedAt: "2024-06-15",
    trending: true,
    upvotes: 567,
    downvotes: 15,
  },
  {
    id: "crisis-7",
    title: "Chittagong Hill Tracts Landslide",
    description: "Heavy rainfall triggered landslides. 15 families buried, rescue and rehabilitation needed.",
    type: "flood",
    location: {
      division: "Chittagong",
      district: "Rangamati",
      upazila: "Rangamati Sadar",
      coordinates: { lat: 22.6533, lng: 92.1753 },
    },
    severity: 88,
    affectedPopulation: 500,
    fundingNeeded: 1000000,
    fundingReceived: 350000,
    status: "active",
    verified: true,
    verificationStatus: "community-validated",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: ["https://example.com/news/cht-landslide"],
    createdAt: "2024-06-10",
    updatedAt: "2024-06-14",
    trending: false,
    upvotes: 123,
    downvotes: 4,
  },
  {
    id: "crisis-8",
    title: "Rajshahi Drought - Farmer Livelihood Crisis",
    description: "Severe drought destroyed crops. 5000 farming families facing starvation and debt.",
    type: "livelihood",
    location: {
      division: "Rajshahi",
      district: "Rajshahi",
      upazila: "Paba",
      coordinates: { lat: 24.3745, lng: 88.6042 },
    },
    severity: 70,
    affectedPopulation: 5000,
    fundingNeeded: 3000000,
    fundingReceived: 450000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: [],
    satelliteData: "Satellite imagery shows 40% crop failure",
    createdAt: "2024-05-25",
    updatedAt: "2024-06-12",
    trending: false,
    upvotes: 89,
    downvotes: 2,
  },
  {
    id: "crisis-9",
    title: "Barisal Coastal Erosion - Displaced Families",
    description: "River erosion destroyed 300 homes. Families need relocation and livelihood support.",
    type: "livelihood",
    location: {
      division: "Barisal",
      district: "Barisal",
      upazila: "Barisal Sadar",
      coordinates: { lat: 22.701, lng: 90.3535 },
    },
    severity: 65,
    affectedPopulation: 1500,
    fundingNeeded: 1800000,
    fundingReceived: 600000,
    status: "recovery",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: [],
    createdAt: "2024-04-15",
    updatedAt: "2024-06-01",
    trending: false,
    upvotes: 67,
    downvotes: 1,
  },
  {
    id: "crisis-10",
    title: "Emerging: Cox's Bazar Rohingya Camp Medical Crisis",
    description: "Disease outbreak in refugee camps. Urgent medical supplies and treatment needed.",
    type: "medical",
    location: {
      division: "Chittagong",
      district: "Cox's Bazar",
      upazila: "Ukhiya",
      coordinates: { lat: 21.2104, lng: 92.0595 },
    },
    severity: 82,
    affectedPopulation: 8000,
    fundingNeeded: 2500000,
    fundingReceived: 0,
    status: "emerging",
    verified: false,
    verificationStatus: "under-review",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: ["https://example.com/news/coxs-bazar-health"],
    createdAt: "2024-06-15",
    updatedAt: "2024-06-15",
    trending: true,
    upvotes: 45,
    downvotes: 3,
  },
]

// Mock Providers
export const mockProviders: Provider[] = [
  {
    id: "provider-1",
    organizationName: "BRAC Khulna",
    registrationType: "ngo",
    email: "khulna@brac.net",
    phone: "+880-1-800-800-100",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=BRAC",
    description: "BRAC - one of the largest NGOs in Bangladesh, working in disaster relief and development.",
    registrationCertificate: "cert-123",
    bankStatement: "bank-stmt-123",
    officeAddressProof: "office-proof-123",
    portfolioImages: ["/ngo-distribution.jpg"],
    leadershipNIDCopies: ["nid-123", "nid-124"],
    references: [{ organizationName: "UN Office", contactPerson: "Ahmed", email: "ahmed@un.org" }],
    trustScore: 95,
    completionRate: 98,
    averageRating: 4.8,
    responseTimeHours: 4,
    yearsActive: 15,
    fraudIncidents: 0,
    specialization: ["flood", "medical", "education"],
    geographicFocus: {
      divisions: ["Khulna", "Sylhet"],
      districts: ["Khulna", "Satkhira", "Sylhet"],
    },
    maxActiveBeneficiaries: 500,
    monthlyFundCap: 10000000,
    totalAidedBeneficiaries: 2450,
    verified: true,
    status: "active",
    badges: ["zero-fraud", "5-year-verified", "100-families"],
    createdAt: "2009-03-15",
    lastActivityAt: "2024-06-15",
  },
  {
    id: "provider-2",
    organizationName: "Coastal Relief Organization",
    registrationType: "ngo",
    email: "info@coastalrelief.org",
    phone: "+880-2-9893445",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=CRO",
    description: "Community-based organization focused on coastal district disaster relief.",
    registrationCertificate: "cert-456",
    bankStatement: "bank-stmt-456",
    officeAddressProof: "office-proof-456",
    portfolioImages: ["/relief-distribution.jpg"],
    leadershipNIDCopies: ["nid-125", "nid-126"],
    references: [{ organizationName: "Local Admin", contactPerson: "Fatima", email: "fatima@local.gov" }],
    trustScore: 78,
    completionRate: 92,
    averageRating: 4.2,
    responseTimeHours: 12,
    yearsActive: 8,
    fraudIncidents: 0,
    specialization: ["flood", "livelihood"],
    geographicFocus: {
      divisions: ["Khulna", "Chittagong"],
      districts: ["Satkhira", "Bagerhat", "Cox's Bazar"],
    },
    maxActiveBeneficiaries: 200,
    monthlyFundCap: 5000000,
    totalAidedBeneficiaries: 890,
    verified: true,
    status: "active",
    badges: ["zero-fraud", "100-families"],
    createdAt: "2016-07-20",
    lastActivityAt: "2024-06-13",
  },
  {
    id: "provider-3",
    organizationName: "Sylhet Volunteer Group",
    registrationType: "volunteer",
    email: "contact@sylhethelp.info",
    phone: "+880-1-7234-445",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=SVG",
    description: "Local volunteer group providing emergency aid and community support.",
    registrationCertificate: "cert-789",
    bankStatement: "bank-stmt-789",
    officeAddressProof: "office-proof-789",
    portfolioImages: ["/volunteer-team.jpg"],
    leadershipNIDCopies: ["nid-127"],
    references: [{ organizationName: "Community Elder", contactPerson: "Rashid", email: "rashid@community.local" }],
    trustScore: 42,
    completionRate: 75,
    averageRating: 3.8,
    responseTimeHours: 48,
    yearsActive: 2,
    fraudIncidents: 0,
    specialization: ["flood", "education"],
    geographicFocus: {
      divisions: ["Sylhet"],
      districts: ["Sylhet", "Sunamganj"],
    },
    maxActiveBeneficiaries: 50,
    monthlyFundCap: 1000000,
    totalAidedBeneficiaries: 120,
    verified: true,
    status: "active",
    badges: [],
    createdAt: "2022-05-10",
    lastActivityAt: "2024-06-10",
  },
  {
    id: "provider-4",
    organizationName: "Dhaka Medical Aid Foundation",
    registrationType: "ngo",
    email: "info@dmafd.org",
    phone: "+880-2-8821234",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=DMAF",
    description: "Specialized in providing medical assistance to underprivileged patients across Bangladesh.",
    registrationCertificate: "cert-234",
    bankStatement: "bank-stmt-234",
    officeAddressProof: "office-proof-234",
    portfolioImages: ["/medical-facility.jpg"],
    leadershipNIDCopies: ["nid-128", "nid-129"],
    references: [{ organizationName: "Dhaka Medical College", contactPerson: "Dr. Rahman", email: "rahman@dmc.edu" }],
    trustScore: 88,
    completionRate: 95,
    averageRating: 4.6,
    responseTimeHours: 6,
    yearsActive: 10,
    fraudIncidents: 0,
    specialization: ["medical"],
    geographicFocus: {
      divisions: ["Dhaka", "Chittagong", "Sylhet"],
      districts: ["Dhaka", "Chattogram", "Sylhet"],
    },
    maxActiveBeneficiaries: 300,
    monthlyFundCap: 8000000,
    totalAidedBeneficiaries: 1560,
    verified: true,
    status: "active",
    badges: ["zero-fraud", "quick-responder", "5-year-verified"],
    createdAt: "2014-08-20",
    lastActivityAt: "2024-06-15",
  },
  {
    id: "provider-5",
    organizationName: "Education for All Bangladesh",
    registrationType: "ngo",
    email: "contact@efabd.org",
    phone: "+880-1-9876-5432",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=EFA",
    description: "Dedicated to providing educational support and materials to underprivileged children.",
    registrationCertificate: "cert-567",
    bankStatement: "bank-stmt-567",
    officeAddressProof: "office-proof-567",
    portfolioImages: ["/school-students-classroom.jpg"],
    leadershipNIDCopies: ["nid-130"],
    references: [{ organizationName: "Ministry of Education", contactPerson: "Kamal", email: "kamal@moe.gov" }],
    trustScore: 72,
    completionRate: 88,
    averageRating: 4.1,
    responseTimeHours: 24,
    yearsActive: 6,
    fraudIncidents: 0,
    specialization: ["education", "poverty"],
    geographicFocus: {
      divisions: ["Rangpur", "Rajshahi", "Mymensingh"],
      districts: ["Dinajpur", "Rajshahi", "Mymensingh"],
    },
    maxActiveBeneficiaries: 150,
    monthlyFundCap: 3000000,
    totalAidedBeneficiaries: 650,
    verified: true,
    status: "active",
    badges: ["100-families"],
    createdAt: "2018-03-12",
    lastActivityAt: "2024-06-14",
  },
  {
    id: "provider-6",
    organizationName: "Rapid Response Team Dhaka",
    registrationType: "volunteer",
    email: "emergency@rrtdhaka.org",
    phone: "+880-1-5555-1234",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=RRT",
    description: "Emergency response team specializing in fire and disaster immediate relief.",
    registrationCertificate: "cert-890",
    bankStatement: "bank-stmt-890",
    officeAddressProof: "office-proof-890",
    portfolioImages: ["/placeholder-sbne4.png"],
    leadershipNIDCopies: ["nid-131", "nid-132"],
    references: [{ organizationName: "Fire Service", contactPerson: "Hasan", email: "hasan@fire.gov" }],
    trustScore: 65,
    completionRate: 82,
    averageRating: 4.0,
    responseTimeHours: 8,
    yearsActive: 4,
    fraudIncidents: 0,
    specialization: ["fire", "flood"],
    geographicFocus: {
      divisions: ["Dhaka"],
      districts: ["Dhaka", "Gazipur", "Narayanganj"],
    },
    maxActiveBeneficiaries: 100,
    monthlyFundCap: 2000000,
    totalAidedBeneficiaries: 340,
    verified: true,
    status: "active",
    badges: ["quick-responder"],
    createdAt: "2020-01-15",
    lastActivityAt: "2024-06-15",
  },
]

// Mock Beneficiaries
export const mockBeneficiaries: Beneficiary[] = [
  {
    id: "beneficiary-1",
    nidNumber: "1234567890123",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=amina",
    fullName: "Amina Begum",
    age: 32,
    phone: "+88017XXXXXXXX",
    address: "House 5, Village Kazipur, Satkhira Sadar",
    location: {
      division: "Khulna",
      district: "Satkhira",
      upazila: "Satkhira Sadar",
      coordinates: { lat: 22.35, lng: 89.08 },
    },
    needCategory: "shelter",
    needDescription:
      "House completely destroyed by recent cyclone. Need materials for rebuilding. Family of 5 currently homeless.",
    amountRequested: 20000,
    urgencyLevel: "critical",
    itemizedBreakdown: [
      { item: "Corrugated tin sheets", cost: 8000 },
      { item: "Wood and bamboo", cost: 7000 },
      { item: "Nails and cement", cost: 5000 },
    ],
    crisisProofImages: ["/cyclone-damage-homes.jpg"],
    familySize: 5,
    dependents: 3,
    dependentDetails: [
      { name: "Rahim (son)", age: 10 },
      { name: "Noor (daughter)", age: 8 },
      { name: "Ali (son)", age: 5 },
    ],
    incomeSources: ["Agriculture", "Day labor"],
    geographicPreference: "local",
    organizationSizePreference: "medium",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXX",
    applicationStatus: "completed",
    verificationStatus: "verified",
    privacyMode: "limited",
    allocatedProviderId: "provider-2",
    providerRating: 5,
    providerFeedback:
      "Excellent service, very quick and professional. They verified my family and delivered materials within 3 days.",
    appliedDate: "2024-06-05",
    allocationDate: "2024-06-07",
    completionDate: "2024-06-12",
    impactStory:
      "With the building materials from this aid, we rebuilt our house roof. Our family now has shelter from the monsoon.",
  },
  {
    id: "beneficiary-2",
    nidNumber: "9876543210987",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=mohammad",
    fullName: "Mohammad Karim",
    age: 45,
    phone: "+88018XXXXXXXX",
    address: "School Road, Sylhet Sadar",
    location: {
      division: "Sylhet",
      district: "Sylhet",
      upazila: "Sylhet Sadar",
      coordinates: { lat: 24.89, lng: 91.87 },
    },
    needCategory: "education",
    needDescription:
      "Son unable to attend school due to fees and materials cost. Bright student but family financial crisis.",
    amountRequested: 5000,
    urgencyLevel: "high",
    itemizedBreakdown: [
      { item: "Annual school fees", cost: 2000 },
      { item: "Books and stationery", cost: 2000 },
      { item: "Uniforms", cost: 1000 },
    ],
    crisisProofImages: ["/school-admission-letter.jpg"],
    familySize: 6,
    dependents: 4,
    dependentDetails: [
      { name: "Sajid (son)", age: 15, education: "School" },
      { name: "Sara (daughter)", age: 12, education: "School" },
      { name: "Hasan (son)", age: 8, education: "School" },
      { name: "Leila (daughter)", age: 5, education: "Pre-school" },
    ],
    incomeSources: ["Small business - Shop keeping"],
    organizationSizePreference: "medium",
    geographicPreference: "local",
    paymentMethod: "bank",
    accountNumber: "XXX-XXXX-XXXX-XXXX",
    applicationStatus: "in-progress",
    verificationStatus: "verified",
    privacyMode: "anonymous",
    appliedDate: "2024-06-10",
    allocatedProviderId: "provider-3",
    allocationDate: "2024-06-12",
  },
  {
    id: "beneficiary-3",
    nidNumber: "5555555555555",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=fatima",
    fullName: "Fatima Khatun",
    age: 68,
    phone: "+88019XXXXXXXX",
    address: "Old Town, Sylhet Sadar",
    location: {
      division: "Sylhet",
      district: "Sylhet",
      upazila: "Sylhet Sadar",
      coordinates: { lat: 24.9, lng: 91.86 },
    },
    needCategory: "food",
    needDescription: "Elderly widow struggling with food security. Son cannot support adequately. Winter approaching.",
    amountRequested: 3000,
    urgencyLevel: "high",
    itemizedBreakdown: [
      { item: "Rice (20kg)", cost: 1000 },
      { item: "Lentils and pulses", cost: 800 },
      { item: "Cooking oil and salt", cost: 600 },
      { item: "Blankets for winter", cost: 600 },
    ],
    crisisProofImages: ["/elderly-home.jpg"],
    familySize: 1,
    dependents: 0,
    dependentDetails: [],
    incomeSources: ["Widow pension - 2000 BDT/month"],
    organizationSizePreference: "small",
    geographicPreference: "local",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXY",
    applicationStatus: "matched",
    verificationStatus: "verified",
    privacyMode: "limited",
    appliedDate: "2024-06-14",
    allocatedProviderId: "provider-3",
    allocationDate: "2024-06-15",
  },
  {
    id: "beneficiary-4",
    nidNumber: "1111222233334",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=rahman",
    fullName: "Abdul Rahman",
    age: 38,
    phone: "+88016XXXXXXXX",
    address: "Village Rampur, Sunamganj Sadar",
    location: {
      division: "Sylhet",
      district: "Sunamganj",
      upazila: "Sunamganj Sadar",
      coordinates: { lat: 25.07, lng: 91.39 },
    },
    needCategory: "livelihood",
    needDescription: "Lost fishing boat and nets in flood. Need equipment to restart livelihood.",
    amountRequested: 15000,
    urgencyLevel: "emergency",
    itemizedBreakdown: [
      { item: "Fishing nets", cost: 8000 },
      { item: "Boat repair materials", cost: 5000 },
      { item: "Fishing equipment", cost: 2000 },
    ],
    crisisProofImages: ["/placeholder-sbne4.png"],
    familySize: 7,
    dependents: 5,
    dependentDetails: [{ name: "Children (5)", age: 12 }],
    incomeSources: ["Fishing (currently unable)"],
    geographicPreference: "local",
    organizationSizePreference: "medium",
    paymentMethod: "nagad",
    accountNumber: "01XXXXXXXXZ",
    applicationStatus: "completed",
    verificationStatus: "verified",
    privacyMode: "public",
    appliedDate: "2024-06-08",
    allocatedProviderId: "provider-3",
    allocationDate: "2024-06-09",
    completionDate: "2024-06-14",
    providerRating: 4,
    providerFeedback: "Good service, but took a bit longer than expected. Overall satisfied.",
    impactStory: "Received new fishing nets and repaired my boat. Back to fishing and earning for my family.",
  },
  {
    id: "beneficiary-5",
    nidNumber: "7777888899990",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=nasrin",
    fullName: "Nasrin Akter",
    age: 28,
    phone: "+88015XXXXXXXX",
    address: "Medical Road, Sylhet City",
    location: {
      division: "Sylhet",
      district: "Sylhet",
      upazila: "Sylhet Sadar",
      coordinates: { lat: 24.91, lng: 91.88 },
    },
    needCategory: "medical",
    needDescription: "Daughter needs urgent surgery. Cannot afford hospital fees.",
    amountRequested: 25000,
    urgencyLevel: "critical",
    itemizedBreakdown: [
      { item: "Surgery fees", cost: 18000 },
      { item: "Medicines", cost: 5000 },
      { item: "Hospital stay", cost: 2000 },
    ],
    crisisProofImages: ["/medical-facility.jpg"],
    familySize: 4,
    dependents: 2,
    dependentDetails: [
      { name: "Ayesha (daughter)", age: 6, education: "Requires surgery" },
      { name: "Rafi (son)", age: 3 },
    ],
    incomeSources: ["Garment worker - 8000 BDT/month"],
    geographicPreference: "national",
    organizationSizePreference: "large",
    paymentMethod: "bank",
    accountNumber: "XXX-YYYY-ZZZZ",
    applicationStatus: "in-progress",
    verificationStatus: "verified",
    privacyMode: "limited",
    appliedDate: "2024-06-12",
    allocatedProviderId: "provider-4",
    allocationDate: "2024-06-13",
  },
  {
    id: "beneficiary-6",
    nidNumber: "4444555566667",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=habib",
    fullName: "Habibullah Mia",
    age: 52,
    phone: "+88014XXXXXXXX",
    address: "Char Area, Sunamganj",
    location: {
      division: "Sylhet",
      district: "Sunamganj",
      upazila: "Tahirpur",
      coordinates: { lat: 25.03, lng: 91.42 },
    },
    needCategory: "food",
    needDescription: "Flood destroyed crops. Family has no food for next 2 months.",
    amountRequested: 8000,
    urgencyLevel: "emergency",
    itemizedBreakdown: [
      { item: "Rice (50kg)", cost: 2500 },
      { item: "Lentils and vegetables", cost: 2000 },
      { item: "Cooking oil and spices", cost: 1500 },
      { item: "Emergency supplies", cost: 2000 },
    ],
    crisisProofImages: ["/placeholder-sbne4.png"],
    familySize: 8,
    dependents: 6,
    dependentDetails: [{ name: "Family members", age: 0 }],
    incomeSources: ["Farmer (crops destroyed)"],
    geographicPreference: "local",
    organizationSizePreference: "small",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXA",
    applicationStatus: "verified",
    verificationStatus: "verified",
    privacyMode: "anonymous",
    appliedDate: "2024-06-13",
  },
  {
    id: "beneficiary-7",
    nidNumber: "2222333344445",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=sultana",
    fullName: "Sultana Begum",
    age: 35,
    phone: "+88013XXXXXXXX",
    address: "Korail Slum, Dhaka",
    location: {
      division: "Dhaka",
      district: "Dhaka",
      upazila: "Gulshan",
      coordinates: { lat: 23.79, lng: 90.41 },
    },
    needCategory: "shelter",
    needDescription: "Lost home in slum fire. Need temporary shelter materials urgently.",
    amountRequested: 12000,
    urgencyLevel: "critical",
    itemizedBreakdown: [
      { item: "Tarpaulin sheets", cost: 4000 },
      { item: "Bamboo poles", cost: 3000 },
      { item: "Rope and nails", cost: 2000 },
      { item: "Emergency supplies", cost: 3000 },
    ],
    crisisProofImages: ["/placeholder-sbne4.png"],
    familySize: 4,
    dependents: 2,
    dependentDetails: [
      { name: "Mina (daughter)", age: 7 },
      { name: "Rahim (son)", age: 4 },
    ],
    incomeSources: ["Domestic worker - 6000 BDT/month"],
    geographicPreference: "local",
    organizationSizePreference: "medium",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXB",
    applicationStatus: "matched",
    verificationStatus: "verified",
    privacyMode: "limited",
    appliedDate: "2024-06-14",
    allocatedProviderId: "provider-6",
    allocationDate: "2024-06-15",
  },
  {
    id: "beneficiary-8",
    nidNumber: "8888999900001",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=jalal",
    fullName: "Jalal Uddin",
    age: 42,
    phone: "+88012XXXXXXXX",
    address: "Village Paba, Rajshahi",
    location: {
      division: "Rajshahi",
      district: "Rajshahi",
      upazila: "Paba",
      coordinates: { lat: 24.37, lng: 88.6 },
    },
    needCategory: "livelihood",
    needDescription: "Drought destroyed entire crop. Need seeds and irrigation support for next season.",
    amountRequested: 18000,
    urgencyLevel: "high",
    itemizedBreakdown: [
      { item: "Seeds (rice, vegetables)", cost: 8000 },
      { item: "Fertilizer", cost: 5000 },
      { item: "Irrigation equipment", cost: 5000 },
    ],
    crisisProofImages: ["/placeholder-sbne4.png"],
    familySize: 6,
    dependents: 4,
    dependentDetails: [{ name: "Children (4)", age: 10 }],
    incomeSources: ["Farming (currently no income)"],
    geographicPreference: "local",
    organizationSizePreference: "medium",
    paymentMethod: "nagad",
    accountNumber: "01XXXXXXXXC",
    applicationStatus: "pending",
    verificationStatus: "under-review",
    privacyMode: "public",
    appliedDate: "2024-06-15",
  },
]

// Mock Donations - EXPANDED
export const mockDonations: Donation[] = [
  {
    id: "donation-1",
    donorId: "donor-1",
    crisisId: "crisis-1",
    amount: 10000,
    message: "Hope this helps the flood victims. Stay strong!",
    status: "completed",
    providerPreference: {
      positive: ["provider-1"],
      negative: [],
      geographicFocus: "Sylhet",
    },
    allocations: [
      {
        id: "alloc-1",
        donationId: "donation-1",
        beneficiaryId: "beneficiary-1",
        providerId: "provider-1",
        allocatedAmount: 10000,
        status: "completed",
        createdAt: "2024-06-07",
      },
    ],
    createdAt: "2024-06-06",
    refundSettings: {
      autoRefund: true,
      refundDays: 60,
    },
    transactionFee: 250,
  },
  {
    id: "donation-2",
    donorId: "donor-1",
    crisisId: "crisis-2",
    amount: 25000,
    message: "For cyclone victims. Praying for quick recovery.",
    status: "in-progress",
    providerPreference: {
      positive: ["provider-2"],
      negative: [],
      geographicFocus: "Khulna",
    },
    allocations: [
      {
        id: "alloc-2",
        donationId: "donation-2",
        beneficiaryId: "beneficiary-2",
        providerId: "provider-2",
        allocatedAmount: 25000,
        status: "in-progress",
        createdAt: "2024-06-10",
      },
    ],
    createdAt: "2024-06-09",
    refundSettings: {
      autoRefund: true,
      refundDays: 90,
    },
    transactionFee: 625,
  },
  {
    id: "donation-3",
    donorId: "donor-1",
    crisisId: "crisis-3",
    amount: 5000,
    message: "For medical treatment. Every life matters.",
    status: "verified",
    providerPreference: {
      positive: [],
      negative: [],
      geographicFocus: "Dhaka",
    },
    allocations: [
      {
        id: "alloc-3",
        donationId: "donation-3",
        beneficiaryId: "beneficiary-5",
        providerId: "provider-4",
        allocatedAmount: 5000,
        status: "verified",
        createdAt: "2024-06-11",
      },
    ],
    createdAt: "2024-06-11",
    refundSettings: {
      autoRefund: false,
    },
    transactionFee: 125,
  },
  {
    id: "donation-4",
    donorId: "donor-2",
    crisisId: "crisis-1",
    amount: 15000,
    message: "Supporting Sylhet flood relief efforts.",
    status: "completed",
    providerPreference: {
      positive: [],
      negative: [],
      geographicFocus: "Sylhet",
    },
    allocations: [
      {
        id: "alloc-4",
        donationId: "donation-4",
        beneficiaryId: "beneficiary-4",
        providerId: "provider-3",
        allocatedAmount: 15000,
        status: "completed",
        createdAt: "2024-06-09",
      },
    ],
    createdAt: "2024-06-08",
    refundSettings: {
      autoRefund: true,
      refundDays: 60,
    },
    transactionFee: 375,
  },
  {
    id: "donation-5",
    donorId: "donor-2",
    crisisId: "crisis-4",
    amount: 8000,
    message: "Education is the key to breaking poverty. Supporting students.",
    status: "in-progress",
    providerPreference: {
      positive: ["provider-5"],
      negative: [],
      crisisTypeFilter: ["education"],
    },
    allocations: [
      {
        id: "alloc-5",
        donationId: "donation-5",
        beneficiaryId: "beneficiary-2",
        providerId: "provider-3",
        allocatedAmount: 5000,
        status: "in-progress",
        createdAt: "2024-06-12",
      },
    ],
    createdAt: "2024-06-11",
    refundSettings: {
      autoRefund: true,
      refundDays: 90,
    },
    transactionFee: 200,
  },
  {
    id: "donation-6",
    donorId: "donor-3",
    crisisId: "crisis-6",
    amount: 30000,
    message: "Urgent help for fire victims. May Allah help them.",
    status: "provider-accepted",
    providerPreference: {
      positive: ["provider-6"],
      negative: [],
      geographicFocus: "Dhaka",
    },
    allocations: [
      {
        id: "alloc-6",
        donationId: "donation-6",
        beneficiaryId: "beneficiary-7",
        providerId: "provider-6",
        allocatedAmount: 12000,
        status: "provider-accepted",
        createdAt: "2024-06-15",
      },
    ],
    createdAt: "2024-06-14",
    refundSettings: {
      autoRefund: true,
      refundDays: 30,
    },
    transactionFee: 750,
  },
  {
    id: "donation-7",
    donorId: "donor-3",
    crisisId: "crisis-5",
    amount: 12000,
    message: "Winter blankets for vulnerable families.",
    status: "pending",
    providerPreference: {
      positive: [],
      negative: [],
      geographicFocus: "Mymensingh",
    },
    allocations: [],
    createdAt: "2024-06-15",
    refundSettings: {
      autoRefund: true,
      refundDays: 60,
    },
    transactionFee: 300,
  },
  {
    id: "donation-8",
    donorId: "donor-4",
    crisisId: "crisis-2",
    amount: 20000,
    message: "Helping cyclone-affected families rebuild their lives.",
    status: "completed",
    providerPreference: {
      positive: ["provider-2"],
      negative: [],
    },
    allocations: [
      {
        id: "alloc-7",
        donationId: "donation-8",
        beneficiaryId: "beneficiary-1",
        providerId: "provider-2",
        allocatedAmount: 20000,
        status: "completed",
        createdAt: "2024-06-07",
      },
    ],
    createdAt: "2024-06-06",
    refundSettings: {
      autoRefund: false,
    },
    transactionFee: 500,
  },
  {
    id: "donation-9",
    donorId: "donor-4",
    crisisId: "crisis-3",
    amount: 10000,
    message: "Medical emergency fund. Hope for quick recovery.",
    status: "in-progress",
    providerPreference: {
      positive: ["provider-4"],
      negative: [],
      crisisTypeFilter: ["medical"],
    },
    allocations: [
      {
        id: "alloc-8",
        donationId: "donation-9",
        beneficiaryId: "beneficiary-5",
        providerId: "provider-4",
        allocatedAmount: 10000,
        status: "in-progress",
        createdAt: "2024-06-13",
      },
    ],
    createdAt: "2024-06-12",
    refundSettings: {
      autoRefund: true,
      refundDays: 45,
    },
    transactionFee: 250,
  },
  {
    id: "donation-10",
    donorId: "donor-5",
    crisisId: "crisis-8",
    amount: 18000,
    message: "Supporting farmers affected by drought.",
    status: "pending",
    providerPreference: {
      positive: [],
      negative: [],
      geographicFocus: "Rajshahi",
      crisisTypeFilter: ["livelihood"],
    },
    allocations: [],
    createdAt: "2024-06-15",
    refundSettings: {
      autoRefund: true,
      refundDays: 60,
    },
    transactionFee: 450,
  },
]

// Mock Fraud Alerts for Admin Dashboard
export const mockFraudAlerts: FraudAlert[] = [
  {
    id: "fraud-1",
    type: "duplicate-nid",
    targetId: "beneficiary-suspicious-1",
    targetType: "beneficiary",
    severity: "high",
    description: "NID number 3333444455556 appears in 3 different applications within 7 days",
    evidence: [
      "Application from Dhaka on 2024-06-08",
      "Application from Sylhet on 2024-06-12",
      "Application from Khulna on 2024-06-14",
    ],
    status: "investigating",
    createdAt: "2024-06-14",
  },
  {
    id: "fraud-2",
    type: "cost-outlier",
    targetId: "provider-suspicious-1",
    targetType: "provider",
    severity: "medium",
    description: "Provider 'Quick Relief Org' requesting 65% above regional average for flood relief",
    evidence: [
      "Regional average: ৳3,200 per family",
      "Provider requesting: ৳5,280 per family",
      "Difference: 65% above average",
    ],
    status: "open",
    createdAt: "2024-06-13",
  },
  {
    id: "fraud-3",
    type: "gps-mismatch",
    targetId: "alloc-suspicious-1",
    targetType: "donation",
    severity: "critical",
    description: "Distribution photo GPS location 45km away from beneficiary stated address",
    evidence: [
      "Beneficiary address: Sylhet Sadar (24.89°N, 91.87°E)",
      "Photo GPS: Sunamganj (25.07°N, 91.39°E)",
      "Distance: 45.3 km",
    ],
    status: "open",
    createdAt: "2024-06-15",
  },
  {
    id: "fraud-4",
    type: "suspicious-pattern",
    targetId: "provider-suspicious-2",
    targetType: "provider",
    severity: "high",
    description: "Same 5 beneficiaries appearing in multiple provider applications",
    evidence: [
      "Beneficiary IDs: B-101, B-102, B-103, B-104, B-105",
      "Appeared in 4 different provider applications",
      "All applications within 10 days",
    ],
    status: "investigating",
    createdAt: "2024-06-12",
  },
  {
    id: "fraud-5",
    type: "deepfake",
    targetId: "alloc-suspicious-2",
    targetType: "donation",
    severity: "critical",
    description: "AI detected potential deepfake in distribution verification photo",
    evidence: [
      "Deepfake confidence: 87%",
      "Facial artifacts detected",
      "Lighting inconsistencies",
      "Metadata manipulation suspected",
    ],
    status: "open",
    createdAt: "2024-06-14",
  },
  {
    id: "fraud-6",
    type: "network-fraud",
    targetId: "fraud-ring-1",
    targetType: "provider",
    severity: "critical",
    description: "Network analysis shows 3 providers submitting same beneficiaries with different names",
    evidence: [
      "Same phone numbers across applications",
      "Same bank accounts",
      "Similar submission patterns",
      "Connected IP addresses",
    ],
    status: "investigating",
    createdAt: "2024-06-11",
  },
]

// Mock Blacklist Entries
export const mockBlacklistEntries: BlacklistEntry[] = [
  {
    id: "blacklist-1",
    nid: "6666777788889",
    phone: "+88011XXXXXXXX",
    bankAccount: "XXX-YYYY-1234",
    email: "fraud@example.com",
    fraudType: "duplicate-applications",
    reason: "Applied 5 times with different names but same NID",
    evidence: ["Application screenshots", "NID verification mismatch", "Bank account linked to multiple identities"],
    addedDate: "2024-05-20",
    addedBy: "admin-1",
  },
  {
    id: "blacklist-2",
    nid: "9999000011112",
    phone: "+88010XXXXXXXX",
    fraudType: "fake-documents",
    reason: "Submitted forged NID and medical records",
    evidence: ["NIDW database mismatch", "Document metadata shows editing", "Hospital confirmed records are fake"],
    addedDate: "2024-06-01",
    addedBy: "admin-1",
  },
  {
    id: "blacklist-3",
    email: "scammer@fake.org",
    phone: "+88009XXXXXXXX",
    fraudType: "provider-fraud",
    reason: "Fake NGO registration, never distributed aid",
    evidence: [
      "NGO Bureau confirmed no such registration",
      "Beneficiaries never received aid",
      "Funds withdrawn but no distribution proof",
    ],
    addedDate: "2024-05-15",
    addedBy: "admin-2",
  },
]

// Mock Distribution Proofs for Completed Allocations
export const mockDistributionProofs: DistributionProof[] = [
  {
    id: "proof-1",
    allocationId: "alloc-1",
    preSiteVisitPhotos: ["/pre-visit-1.jpg", "/pre-visit-2.jpg"],
    beneficiaryConsentForm: true,
    distributionPhotos: ["/distribution-1.jpg", "/distribution-2.jpg"],
    distributionVideos: ["/distribution-video-1.mp4"],
    itemsVerified: [
      { item: "Corrugated tin sheets", quantity: 20 },
      { item: "Wood and bamboo", quantity: 50 },
      { item: "Nails and cement", quantity: 1 },
    ],
    beneficiarySignature: "/signature-1.jpg",
    postDistributionPhotos: ["/post-dist-1.jpg", "/post-dist-2.jpg"],
    receiptImages: ["/receipt-1.jpg"],
    beneficiaryConfirmationSMS: true,
    gpsCoordinates: { lat: 22.35, lng: 89.08 },
    timestamp: "2024-06-12T10:30:00Z",
    distributionDate: "2024-06-12",
    deepfakeDetection: true,
    faceMatchScore: 96,
    gpsValidation: true,
    imageQualityScore: 92,
    verificationStatus: "verified",
  },
  {
    id: "proof-2",
    allocationId: "alloc-4",
    preSiteVisitPhotos: ["/pre-visit-3.jpg"],
    beneficiaryConsentForm: true,
    distributionPhotos: ["/distribution-3.jpg", "/distribution-4.jpg"],
    distributionVideos: [],
    itemsVerified: [
      { item: "Fishing nets", quantity: 2 },
      { item: "Boat repair materials", quantity: 1 },
      { item: "Fishing equipment", quantity: 5 },
    ],
    beneficiarySignature: "/signature-2.jpg",
    postDistributionPhotos: ["/post-dist-3.jpg"],
    receiptImages: ["/receipt-2.jpg"],
    beneficiaryConfirmationSMS: true,
    gpsCoordinates: { lat: 25.07, lng: 91.39 },
    timestamp: "2024-06-14T14:15:00Z",
    distributionDate: "2024-06-14",
    deepfakeDetection: true,
    faceMatchScore: 94,
    gpsValidation: true,
    imageQualityScore: 88,
    verificationStatus: "verified",
  },
  {
    id: "proof-3",
    allocationId: "alloc-7",
    preSiteVisitPhotos: ["/pre-visit-4.jpg", "/pre-visit-5.jpg"],
    beneficiaryConsentForm: true,
    distributionPhotos: ["/distribution-5.jpg"],
    distributionVideos: ["/distribution-video-2.mp4"],
    itemsVerified: [
      { item: "Corrugated tin sheets", quantity: 15 },
      { item: "Wood and bamboo", quantity: 40 },
      { item: "Nails and cement", quantity: 1 },
    ],
    beneficiarySignature: "/signature-3.jpg",
    postDistributionPhotos: ["/post-dist-4.jpg", "/post-dist-5.jpg"],
    receiptImages: ["/receipt-3.jpg"],
    bankTransferScreenshots: ["/bank-transfer-1.jpg"],
    beneficiaryConfirmationSMS: true,
    gpsCoordinates: { lat: 22.35, lng: 89.08 },
    timestamp: "2024-06-12T09:45:00Z",
    distributionDate: "2024-06-12",
    deepfakeDetection: true,
    faceMatchScore: 98,
    gpsValidation: true,
    imageQualityScore: 95,
    verificationStatus: "verified",
  },
]
