import type { Crisis, Donation, Provider, Beneficiary, User } from "@/types"

// Mock Bangladesh divisions
const DIVISIONS = ["Dhaka", "Chittagong", "Sylhet", "Khulna", "Rajshahi", "Barisal", "Rangpur", "Mymensingh"]
const DISTRICTS_BY_DIVISION: Record<string, string[]> = {
  Dhaka: ["Dhaka", "Gazipur", "Narayanganj", "Manikganj", "Munshiganj", "Tangail", "Faridpur", "Rajbari"],
  Sylhet: ["Sylhet", "Sunamganj", "Moulvibazar", "Habiganj"],
  Khulna: ["Khulna", "Satkhira", "Bagerhat", "Jhenaidah", "Magura", "Narail"],
  Chittagong: ["Chattogram", "Cox's Bazar", "Rangamati", "Khagrachari", "Noakhali", "Feni", "Lakshmipur"],
  Rajshahi: ["Rajshahi", "Natore", "Naogaon", "Chapainawabganj", "Pabna", "Bogura"],
  Barisal: ["Barisal", "Patuakhali", "Pirojpur", "Jhalokati", "Bhola"],
  Rangpur: ["Rangpur", "Dinajpur", "Thakurgaon", "Panchagarh", "Lalmonirhat", "Kurigram", "Gaibandha"],
  Mymensingh: ["Mymensingh", "Jamalpur", "Sherpur", "Netrokona"],
}

// Mock Donors
export const mockDonors: User[] = [
  {
    id: "donor-1",
    role: "donor",
    name: "Rashed Ahmed",
    email: "rashed@example.com",
    phone: "+88017XXXXXXXX",
    verified: true,
    createdAt: "2024-01-15",
  },
  {
    id: "donor-2",
    role: "donor",
    name: "Fatima Rahman",
    email: "fatima@example.com",
    phone: "+88018XXXXXXXX",
    verified: true,
    createdAt: "2024-02-20",
  },
  {
    id: "donor-3",
    role: "donor",
    name: "Karim Hassan",
    email: "karim@example.com",
    phone: "+88019XXXXXXXX",
    verified: true,
    createdAt: "2024-03-10",
  },
]

// Mock Crises
export const mockCrises: Crisis[] = [
  {
    id: "crisis-1",
    title: "Sylhet Monsoon Flooding 2024",
    description:
      "Heavy monsoon rains have caused severe flooding affecting over 50,000 people. Emergency shelter and food supplies urgently needed.",
    type: "flood",
    location: {
      division: "Sylhet",
      district: "Sylhet",
      upazila: "Sylhet Sadar",
      coordinates: { lat: 24.8949, lng: 91.8687 },
    },
    severity: 92,
    affectedPopulation: 48500,
    fundingNeeded: 5000000,
    fundingReceived: 1250000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: ["https://example.com/news/sylhet-flood"],
    satelliteData: "NASA satellite confirms 15% area inundation",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-15",
    trending: true,
    upvotes: 456,
    downvotes: 12,
  },
  {
    id: "crisis-2",
    title: "Satkhira Cyclone Recovery",
    description: "Recent cyclone destroyed 2000+ homes. Rebuilding materials and temporary shelter urgently needed.",
    type: "flood",
    location: {
      division: "Khulna",
      district: "Satkhira",
      upazila: "Satkhira Sadar",
      coordinates: { lat: 22.348, lng: 89.078 },
    },
    severity: 85,
    affectedPopulation: 32000,
    fundingNeeded: 3200000,
    fundingReceived: 850000,
    status: "active",
    verified: true,
    verificationStatus: "community-validated",
    evidenceImages: ["/cyclone-damage-homes.jpg"],
    newsLinks: ["https://example.com/news/satkhira-cyclone"],
    createdAt: "2024-05-20",
    updatedAt: "2024-06-10",
    trending: true,
    upvotes: 234,
    downvotes: 8,
  },
  {
    id: "crisis-3",
    title: "Medical Emergency Response - Cancer Ward",
    description: "Underprivileged cancer patients need treatment fees. Emergency medical fund established.",
    type: "medical",
    location: {
      division: "Dhaka",
      district: "Dhaka",
      upazila: "Dhaka Sadar",
      coordinates: { lat: 23.8103, lng: 90.4125 },
    },
    severity: 78,
    affectedPopulation: 250,
    fundingNeeded: 1500000,
    fundingReceived: 420000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/medical-facility.jpg"],
    newsLinks: [],
    createdAt: "2024-06-05",
    updatedAt: "2024-06-12",
    trending: false,
    upvotes: 189,
    downvotes: 3,
  },
  {
    id: "crisis-4",
    title: "Back-to-School Fund for Underprivileged",
    description: "5000 students unable to afford school materials. Education is the key to breaking poverty cycles.",
    type: "education",
    location: {
      division: "Rangpur",
      district: "Dinajpur",
      upazila: "Dinajpur Sadar",
      coordinates: { lat: 25.6358, lng: 88.6441 },
    },
    severity: 62,
    affectedPopulation: 5000,
    fundingNeeded: 2000000,
    fundingReceived: 600000,
    status: "active",
    verified: true,
    verificationStatus: "under-review",
    evidenceImages: ["/school-students-classroom.jpg"],
    newsLinks: [],
    createdAt: "2024-06-08",
    updatedAt: "2024-06-13",
    trending: false,
    upvotes: 167,
    downvotes: 5,
  },
  {
    id: "crisis-5",
    title: "Winter Poverty Crisis - Vulnerable Families",
    description:
      "Winter approaching. 10,000 families without proper clothing and blankets. Temperature drops below 5°C.",
    type: "poverty",
    location: {
      division: "Mymensingh",
      district: "Mymensingh",
      upazila: "Mymensingh Sadar",
      coordinates: { lat: 24.7471, lng: 90.4203 },
    },
    severity: 74,
    affectedPopulation: 10000,
    fundingNeeded: 2500000,
    fundingReceived: 500000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/winter-poverty-families.jpg"],
    newsLinks: [],
    createdAt: "2024-11-01",
    updatedAt: "2024-11-05",
    trending: true,
    upvotes: 298,
    downvotes: 6,
  },
]

// Mock Providers
export const mockProviders: Provider[] = [
  {
    id: "provider-1",
    organizationName: "BRAC Khulna",
    registrationType: "ngo",
    email: "khulna@brac.net",
    phone: "+880-1-800-800-100",
    description: "BRAC - one of the largest NGOs in Bangladesh, working in disaster relief and development.",
    registrationCertificate: "cert-123",
    bankStatement: "bank-stmt-123",
    officeAddressProof: "office-proof-123",
    portfolioImages: ["/ngo-distribution.jpg"],
    leadershipNIDCopies: ["nid-123", "nid-124"],
    references: [{ organizationName: "UN Office", contactPerson: "Ahmed", email: "ahmed@un.org" }],
    trustScore: 95,
    completionRate: 98,
    averageRating: 4.8,
    responseTimeHours: 4,
    yearsActive: 15,
    fraudIncidents: 0,
    specialization: ["flood", "medical", "education"],
    geographicFocus: {
      divisions: ["Khulna", "Sylhet"],
      districts: ["Khulna", "Satkhira", "Sylhet"],
    },
    maxActiveBeneficiaries: 500,
    monthlyFundCap: 10000000,
    totalAidedBeneficiaries: 2450,
    verified: true,
    status: "active",
    badges: ["zero-fraud", "5-year-verified"],
    createdAt: "2009-03-15",
    lastActivityAt: "2024-06-15",
  },
  {
    id: "provider-2",
    organizationName: "Coastal Relief Organization",
    registrationType: "ngo",
    email: "info@coastalrelief.org",
    phone: "+880-2-9893445",
    description: "Community-based organization focused on coastal district disaster relief.",
    registrationCertificate: "cert-456",
    bankStatement: "bank-stmt-456",
    officeAddressProof: "office-proof-456",
    portfolioImages: ["/relief-distribution.jpg"],
    leadershipNIDCopies: ["nid-125", "nid-126"],
    references: [{ organizationName: "Local Admin", contactPerson: "Fatima", email: "fatima@local.gov" }],
    trustScore: 78,
    completionRate: 92,
    averageRating: 4.2,
    responseTimeHours: 12,
    yearsActive: 8,
    fraudIncidents: 0,
    specialization: ["flood", "livelihood"],
    geographicFocus: {
      divisions: ["Khulna", "Chittagong"],
      districts: ["Satkhira", "Bagerhat", "Cox's Bazar"],
    },
    maxActiveBeneficiaries: 200,
    monthlyFundCap: 5000000,
    totalAidedBeneficiaries: 890,
    verified: true,
    status: "active",
    badges: ["zero-fraud"],
    createdAt: "2016-07-20",
    lastActivityAt: "2024-06-13",
  },
  {
    id: "provider-3",
    organizationName: "Sylhet Volunteer Group",
    registrationType: "volunteer",
    email: "contact@sylhethelpinfo.com",
    phone: "+880-1-7234-445",
    description: "Local volunteer group providing emergency aid and community support.",
    registrationCertificate: "cert-789",
    bankStatement: "bank-stmt-789",
    officeAddressProof: "office-proof-789",
    portfolioImages: ["/volunteer-team.jpg"],
    leadershipNIDCopies: ["nid-127"],
    references: [{ organizationName: "Community Elder", contactPerson: "Rashid", email: "rashid@community.local" }],
    trustScore: 42,
    completionRate: 75,
    averageRating: 3.8,
    responseTimeHours: 48,
    yearsActive: 2,
    fraudIncidents: 0,
    specialization: ["flood", "education"],
    geographicFocus: {
      divisions: ["Sylhet"],
      districts: ["Sylhet", "Sunamganj"],
    },
    maxActiveBeneficiaries: 50,
    monthlyFundCap: 1000000,
    totalAidedBeneficiaries: 120,
    verified: true,
    status: "active",
    badges: [],
    createdAt: "2022-05-10",
    lastActivityAt: "2024-06-10",
  },
]

// Mock Beneficiaries
export const mockBeneficiaries: Beneficiary[] = [
  {
    id: "beneficiary-1",
    nidNumber: "1234567890123",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    fullName: "Amina Begum",
    phone: "+88017XXXXXXXX",
    address: "House 5, Village Kazipur, Satkhira Sadar",
    location: {
      division: "Khulna",
      district: "Satkhira",
      upazila: "Satkhira Sadar",
      coordinates: { lat: 22.35, lng: 89.08 },
    },
    needCategory: "shelter",
    needDescription: "House completely destroyed by recent cyclone. Need materials for rebuilding.",
    amountRequested: 20000,
    urgencyLevel: "critical",
    itemizedBreakdown: [
      { item: "Corrugated tin sheets", cost: 8000 },
      { item: "Wood and bamboo", cost: 7000 },
      { item: "Nails and cement", cost: 5000 },
    ],
    crisisProofImages: ["/house-damage.jpg"],
    familySize: 5,
    dependents: 3,
    incomeSources: ["Agriculture", "Day labor"],
    geographicPreference: "local",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXX",
    applicationStatus: "completed",
    verificationStatus: "verified",
    privacyMode: "limited",
    providerRating: 5,
    providerFeedback: "Excellent service, very quick and professional",
    appliedDate: "2024-06-05",
    allocationDate: "2024-06-07",
    completionDate: "2024-06-12",
  },
  {
    id: "beneficiary-2",
    nidNumber: "9876543210987",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    fullName: "Mohammad Karim",
    phone: "+88018XXXXXXXX",
    address: "School Road, Sylhet Sadar",
    location: {
      division: "Sylhet",
      district: "Sylhet",
      upazila: "Sylhet Sadar",
      coordinates: { lat: 24.89, lng: 91.87 },
    },
    needCategory: "education",
    needDescription: "Son unable to attend school due to fees and materials cost.",
    amountRequested: 5000,
    urgencyLevel: "high",
    itemizedBreakdown: [
      { item: "Annual school fees", cost: 2000 },
      { item: "Books and stationery", cost: 2000 },
      { item: "Uniforms", cost: 1000 },
    ],
    crisisProofImages: ["/school-admission-letter.jpg"],
    familySize: 6,
    dependents: 4,
    incomeSources: ["Small business"],
    organizationSizePreference: "medium",
    paymentMethod: "bank",
    accountNumber: "XXX-XXXX-XXXX-XXXX",
    applicationStatus: "verified",
    verificationStatus: "verified",
    privacyMode: "anonymous",
    appliedDate: "2024-06-10",
  },
]

// Mock Donations - EXPANDED
export const mockDonations: Donation[] = [
  {
    id: "donation-1",
    donorId: "donor-1",
    crisisId: "crisis-1",
    amount: 10000,
    status: "completed",
    providerPreference: {
      positive: ["provider-1"],
      negative: [],
      geographicFocus: "Sylhet",
    },
    allocations: [
      {
        id: "alloc-1",
        donationId: "donation-1",
        beneficiaryId: "beneficiary-1",
        providerId: "provider-1",
        allocatedAmount: 10000,
        status: "completed",
        createdAt: "2024-06-07",
      },
    ],
    createdAt: "2024-06-06",
    refundSettings: {
      autoRefund: true,
      refundDays: 60,
    },
    transactionFee: 250,
  },
  {
    id: "donation-2",
    donorId: "donor-1",
    crisisId: "crisis-2",
    amount: 25000,
    status: "in-progress",
    providerPreference: {
      positive: ["provider-2"],
      negative: [],
      geographicFocus: "Khulna",
    },
    allocations: [
      {
        id: "alloc-2",
        donationId: "donation-2",
        beneficiaryId: "beneficiary-2",
        providerId: "provider-2",
        allocatedAmount: 25000,
        status: "in-progress",
        createdAt: "2024-06-10",
      },
    ],
    createdAt: "2024-06-09",
    refundSettings: {
      autoRefund: true,
      refundDays: 90,
    },
    transactionFee: 625,
  },
  {
    id: "donation-3",
    donorId: "donor-1",
    crisisId: "crisis-3",
    amount: 5000,
    status: "completed",
    providerPreference: {
      positive: [],
      negative: [],
      geographicFocus: "Dhaka",
    },
    allocations: [
      {
        id: "alloc-3",
        donationId: "donation-3",
        beneficiaryId: "beneficiary-1",
        providerId: "provider-1",
        allocatedAmount: 5000,
        status: "completed",
        createdAt: "2024-06-11",
      },
    ],
    createdAt: "2024-06-11",
    refundSettings: {
      autoRefund: false,
    },
    transactionFee: 125,
  },
]
