import type {
  Crisis,
  Donation,
  Provider,
  Beneficiary,
  User,
  FraudAlert,
  BlacklistEntry,
  DistributionProof,
} from "@/types"

// Mock Bangladesh divisions
const DIVISIONS = ["Dhaka", "Chittagong", "Sylhet", "Khulna", "Rajshahi", "Barisal", "Rangpur", "Mymensingh"]
const DISTRICTS_BY_DIVISION: Record<string, string[]> = {
  Dhaka: ["Dhaka", "Gazipur", "Narayanganj", "Manikganj", "Munshiganj", "Tangail", "Faridpur", "Rajbari"],
  Sylhet: ["Sylhet", "Sunamganj", "Moulvibazar", "Habiganj"],
  Khulna: ["Khulna", "Satkhira", "Bagerhat", "Jhenaidah", "Magura", "Narail"],
  Chittagong: ["Chattogram", "Cox's Bazar", "Rangamati", "Khagrachari", "Noakhali", "Feni", "Lakshmipur"],
  Rajshahi: ["Rajshahi", "Natore", "Naogaon", "Chapainawabganj", "Pabna", "Bogura"],
  Barisal: ["Barisal", "Patuakhali", "Pirojpur", "Jhalokati", "Bhola"],
  Rangpur: ["Rangpur", "Dinajpur", "Thakurgaon", "Panchagarh", "Lalmonirhat", "Kurigram", "Gaibandha"],
  Mymensingh: ["Mymensingh", "Jamalpur", "Sherpur", "Netrokona"],
}

// Mock Donors
export const mockDonors: User[] = [
  {
    id: "donor-1",
    role: "donor",
    name: "Rashed Ahmed",
    email: "rashed@example.com",
    phone: "+88017XXXXXXXX",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=rashed",
    verified: true,
    createdAt: "2024-01-15",
  },
  {
    id: "donor-2",
    role: "donor",
    name: "Fatima Rahman",
    email: "fatima@example.com",
    phone: "+88018XXXXXXXX",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=fatima",
    verified: true,
    createdAt: "2024-02-20",
  },
  {
    id: "donor-3",
    role: "donor",
    name: "Karim Hassan",
    email: "karim@example.com",
    phone: "+88019XXXXXXXX",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=karim",
    verified: true,
    createdAt: "2024-03-10",
  },
  {
    id: "donor-4",
    role: "donor",
    name: "Sara Chowdhury",
    email: "sara@example.com",
    phone: "+88016XXXXXXXX",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=sara",
    verified: true,
    createdAt: "2024-04-05",
  },
  {
    id: "donor-5",
    role: "donor",
    name: "Imran Khan",
    email: "imran@example.com",
    phone: "+88015XXXXXXXX",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=imran",
    verified: true,
    createdAt: "2024-05-12",
  },
]

// Mock Crises
export const mockCrises: Crisis[] = [
  {
    id: "crisis-1",
    title: "Sylhet Monsoon Flooding 2024",
    description:
      "Heavy monsoon rains have caused severe flooding affecting over 50,000 people. Emergency shelter and food supplies urgently needed.",
    type: "flood",
    location: {
      division: "Sylhet",
      district: "Sylhet",
      upazila: "Sylhet Sadar",
      coordinates: { lat: 24.8949, lng: 91.8687 },
    },
    severity: 92,
    affectedPopulation: 48500,
    fundingNeeded: 5000000,
    fundingReceived: 3250000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: [
      "/placeholder-sbne4.png",
      "/cyclone-damage-homes.jpg",
      "/medical-facility.jpg"
    ],
    newsLinks: ["https://example.com/news/sylhet-flood"],
    satelliteData: "NASA satellite confirms 15% area inundation",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-15",
    trending: true,
    upvotes: 456,
    downvotes: 12,
    uploadedBy: {
      type: "system",
      name: "AI Detection System"
    }
  },
  {
    id: "crisis-2",
    title: "Satkhira Cyclone Recovery",
    description: "Recent cyclone destroyed 2000+ homes. Rebuilding materials and temporary shelter urgently needed.",
    type: "flood",
    location: {
      division: "Khulna",
      district: "Satkhira",
      upazila: "Satkhira Sadar",
      coordinates: { lat: 22.348, lng: 89.078 },
    },
    severity: 85,
    affectedPopulation: 32000,
    fundingNeeded: 3200000,
    fundingReceived: 1850000,
    status: "active",
    verified: true,
    verificationStatus: "community-validated",
    evidenceImages: [
      "/cyclone-damage-homes.jpg",
      "/placeholder-sbne4.png"
    ],
    newsLinks: ["https://example.com/news/satkhira-cyclone"],
    createdAt: "2024-05-20",
    updatedAt: "2024-06-10",
    trending: true,
    upvotes: 234,
    downvotes: 8,
    uploadedBy: {
      type: "admin",
      name: "Admin User",
      id: "admin-1"
    }
  },
  {
    id: "crisis-3",
    title: "Medical Emergency Response - Cancer Ward",
    description: "Underprivileged cancer patients need treatment fees. Emergency medical fund established.",
    type: "medical",
    location: {
      division: "Dhaka",
      district: "Dhaka",
      upazila: "Dhaka Sadar",
      coordinates: { lat: 23.8103, lng: 90.4125 },
    },
    severity: 78,
    affectedPopulation: 250,
    fundingNeeded: 1500000,
    fundingReceived: 920000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/medical-facility.jpg"],
    newsLinks: [],
    createdAt: "2024-06-05",
    updatedAt: "2024-06-12",
    trending: false,
    upvotes: 189,
    downvotes: 3,
    uploadedBy: {
      type: "provider",
      name: "BRAC Healthcare",
      id: "provider-1"
    }
  },
  {
    id: "crisis-4",
    title: "Back-to-School Fund for Underprivileged",
    description: "5000 students unable to afford school materials. Education is the key to breaking poverty cycles.",
    type: "education",
    location: {
      division: "Rangpur",
      district: "Dinajpur",
      upazila: "Dinajpur Sadar",
      coordinates: { lat: 25.6358, lng: 88.6441 },
    },
    severity: 62,
    affectedPopulation: 5000,
    fundingNeeded: 2000000,
    fundingReceived: 1200000,
    status: "active",
    verified: true,
    verificationStatus: "under-review",
    evidenceImages: ["/school-students-classroom.jpg"],
    newsLinks: [],
    createdAt: "2024-06-08",
    updatedAt: "2024-06-13",
    trending: false,
    upvotes: 167,
    downvotes: 5,
    uploadedBy: {
      type: "provider",
      name: "Jaago Foundation",
      id: "provider-2"
    }
  },
  {
    id: "crisis-5",
    title: "Winter Poverty Crisis - Vulnerable Families",
    description:
      "Winter approaching. 10,000 families without proper clothing and blankets. Temperature drops below 5°C.",
    type: "poverty",
    location: {
      division: "Mymensingh",
      district: "Mymensingh",
      upazila: "Mymensingh Sadar",
      coordinates: { lat: 24.7471, lng: 90.4203 },
    },
    severity: 74,
    affectedPopulation: 10000,
    fundingNeeded: 2500000,
    fundingReceived: 800000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/winter-poverty-families.jpg"],
    newsLinks: [],
    createdAt: "2024-11-01",
    updatedAt: "2024-11-05",
    trending: true,
    upvotes: 298,
    downvotes: 6,
    uploadedBy: {
      type: "system",
      name: "AI Detection System"
    }
  },
  {
    id: "crisis-6",
    title: "Dhaka Slum Fire Emergency",
    description: "Major fire destroyed 500 shanties in Korail slum. 2000+ people homeless, need immediate shelter.",
    type: "fire",
    location: {
      division: "Dhaka",
      district: "Dhaka",
      upazila: "Gulshan",
      coordinates: { lat: 23.7925, lng: 90.4078 },
    },
    severity: 95,
    affectedPopulation: 2000,
    fundingNeeded: 4000000,
    fundingReceived: 1500000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: ["https://example.com/news/dhaka-fire"],
    satelliteData: "Thermal imaging confirms extensive damage",
    createdAt: "2024-06-14",
    updatedAt: "2024-06-15",
    trending: true,
    upvotes: 567,
    downvotes: 15,
    uploadedBy: {
      type: "system",
      name: "AI Detection System"
    }
  },
  {
    id: "crisis-7",
    title: "Chittagong Hill Tracts Landslide",
    description: "Heavy rainfall triggered landslides. 15 families buried, rescue and rehabilitation needed.",
    type: "flood",
    location: {
      division: "Chittagong",
      district: "Rangamati",
      upazila: "Rangamati Sadar",
      coordinates: { lat: 22.6533, lng: 92.1753 },
    },
    severity: 88,
    affectedPopulation: 500,
    fundingNeeded: 1000000,
    fundingReceived: 350000,
    status: "active",
    verified: true,
    verificationStatus: "community-validated",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: ["https://example.com/news/cht-landslide"],
    createdAt: "2024-06-10",
    updatedAt: "2024-06-14",
    trending: false,
    upvotes: 123,
    downvotes: 4,
    uploadedBy: {
      type: "admin",
      name: "District Admin",
      id: "admin-2"
    }
  },
  {
    id: "crisis-8",
    title: "Rajshahi Drought - Farmer Livelihood Crisis",
    description: "Severe drought destroyed crops. 5000 farming families facing starvation and debt.",
    type: "livelihood",
    location: {
      division: "Rajshahi",
      district: "Rajshahi",
      upazila: "Paba",
      coordinates: { lat: 24.3745, lng: 88.6042 },
    },
    severity: 70,
    affectedPopulation: 5000,
    fundingNeeded: 3000000,
    fundingReceived: 450000,
    status: "active",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: [],
    satelliteData: "Satellite imagery shows 40% crop failure",
    createdAt: "2024-05-25",
    updatedAt: "2024-06-12",
    trending: false,
    upvotes: 89,
    downvotes: 2,
    uploadedBy: {
      type: "provider",
      name: "Krishi Foundation",
      id: "provider-3"
    }
  },
  {
    id: "crisis-9",
    title: "Barisal Coastal Erosion - Displaced Families",
    description: "River erosion destroyed 300 homes. Families need relocation and livelihood support.",
    type: "livelihood",
    location: {
      division: "Barisal",
      district: "Barisal",
      upazila: "Barisal Sadar",
      coordinates: { lat: 22.701, lng: 90.3535 },
    },
    severity: 65,
    affectedPopulation: 1500,
    fundingNeeded: 1800000,
    fundingReceived: 600000,
    status: "recovery",
    verified: true,
    verificationStatus: "ai-verified",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: [],
    createdAt: "2024-04-15",
    updatedAt: "2024-06-01",
    trending: false,
    upvotes: 67,
    downvotes: 1,
    uploadedBy: {
      type: "admin",
      name: "Regional Coordinator",
      id: "admin-3"
    }
  },
  {
    id: "crisis-10",
    title: "Emerging: Cox's Bazar Rohingya Camp Medical Crisis",
    description: "Disease outbreak in refugee camps. Urgent medical supplies and treatment needed.",
    type: "medical",
    location: {
      division: "Chittagong",
      district: "Cox's Bazar",
      upazila: "Ukhiya",
      coordinates: { lat: 21.2104, lng: 92.0595 },
    },
    severity: 82,
    affectedPopulation: 8000,
    fundingNeeded: 2500000,
    fundingReceived: 0,
    status: "emerging",
    verified: false,
    verificationStatus: "under-review",
    evidenceImages: ["/placeholder-sbne4.png"],
    newsLinks: ["https://example.com/news/coxs-bazar-health"],
    createdAt: "2024-06-15",
    updatedAt: "2024-06-15",
    trending: true,
    upvotes: 45,
    downvotes: 3,
    uploadedBy: {
      type: "provider",
      name: "Médecins Sans Frontières",
      id: "provider-4"
    }
  },
]

// Mock Providers
export const mockProviders: Provider[] = [
  {
    id: "provider-1",
    organizationName: "BRAC Khulna",
    registrationType: "ngo",
    email: "khulna@brac.net",
    phone: "+880-1-800-800-100",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=BRAC",
    description: "BRAC - one of the largest NGOs in Bangladesh, working in disaster relief and development.",
    registrationCertificate: "cert-123",
    bankStatement: "bank-stmt-123",
    officeAddressProof: "office-proof-123",
    portfolioImages: ["/ngo-distribution.jpg"],
    leadershipNIDCopies: ["nid-123", "nid-124"],
    references: [{ organizationName: "UN Office", contactPerson: "Ahmed", email: "ahmed@un.org" }],
    trustScore: 95,
    completionRate: 98,
    averageRating: 4.8,
    responseTimeHours: 4,
    yearsActive: 15,
    fraudIncidents: 0,
    specialization: ["flood", "medical", "education"],
    geographicFocus: {
      divisions: ["Khulna", "Sylhet"],
      districts: ["Khulna", "Satkhira", "Sylhet"],
    },
    maxActiveBeneficiaries: 500,
    monthlyFundCap: 10000000,
    totalAidedBeneficiaries: 2450,
    verified: true,
    status: "active",
    badges: ["zero-fraud", "5-year-verified", "100-families"],
    createdAt: "2009-03-15",
    lastActivityAt: "2024-06-15",
  },
  {
    id: "provider-2",
    organizationName: "Coastal Relief Organization",
    registrationType: "ngo",
    email: "info@coastalrelief.org",
    phone: "+880-2-9893445",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=CRO",
    description: "Community-based organization focused on coastal district disaster relief.",
    registrationCertificate: "cert-456",
    bankStatement: "bank-stmt-456",
    officeAddressProof: "office-proof-456",
    portfolioImages: ["/relief-distribution.jpg"],
    leadershipNIDCopies: ["nid-125", "nid-126"],
    references: [{ organizationName: "Local Admin", contactPerson: "Fatima", email: "fatima@local.gov" }],
    trustScore: 78,
    completionRate: 92,
    averageRating: 4.2,
    responseTimeHours: 12,
    yearsActive: 8,
    fraudIncidents: 0,
    specialization: ["flood", "livelihood"],
    geographicFocus: {
      divisions: ["Khulna", "Chittagong"],
      districts: ["Satkhira", "Bagerhat", "Cox's Bazar"],
    },
    maxActiveBeneficiaries: 200,
    monthlyFundCap: 5000000,
    totalAidedBeneficiaries: 890,
    verified: true,
    status: "active",
    badges: ["zero-fraud", "100-families"],
    createdAt: "2016-07-20",
    lastActivityAt: "2024-06-13",
  },
  {
    id: "provider-3",
    organizationName: "Sylhet Volunteer Group",
    registrationType: "volunteer",
    email: "contact@sylhethelp.info",
    phone: "+880-1-7234-445",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=SVG",
    description: "Local volunteer group providing emergency aid and community support.",
    registrationCertificate: "cert-789",
    bankStatement: "bank-stmt-789",
    officeAddressProof: "office-proof-789",
    portfolioImages: ["/volunteer-team.jpg"],
    leadershipNIDCopies: ["nid-127"],
    references: [{ organizationName: "Community Elder", contactPerson: "Rashid", email: "rashid@community.local" }],
    trustScore: 42,
    completionRate: 75,
    averageRating: 3.8,
    responseTimeHours: 48,
    yearsActive: 2,
    fraudIncidents: 0,
    specialization: ["flood", "education"],
    geographicFocus: {
      divisions: ["Sylhet"],
      districts: ["Sylhet", "Sunamganj"],
    },
    maxActiveBeneficiaries: 50,
    monthlyFundCap: 1000000,
    totalAidedBeneficiaries: 120,
    verified: true,
    status: "active",
    badges: [],
    createdAt: "2022-05-10",
    lastActivityAt: "2024-06-10",
  },
  {
    id: "provider-4",
    organizationName: "Dhaka Medical Aid Foundation",
    registrationType: "ngo",
    email: "info@dmafd.org",
    phone: "+880-2-8821234",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=DMAF",
    description: "Specialized in providing medical assistance to underprivileged patients across Bangladesh.",
    registrationCertificate: "cert-234",
    bankStatement: "bank-stmt-234",
    officeAddressProof: "office-proof-234",
    portfolioImages: ["/medical-facility.jpg"],
    leadershipNIDCopies: ["nid-128", "nid-129"],
    references: [{ organizationName: "Dhaka Medical College", contactPerson: "Dr. Rahman", email: "rahman@dmc.edu" }],
    trustScore: 88,
    completionRate: 95,
    averageRating: 4.6,
    responseTimeHours: 6,
    yearsActive: 10,
    fraudIncidents: 0,
    specialization: ["medical"],
    geographicFocus: {
      divisions: ["Dhaka", "Chittagong", "Sylhet"],
      districts: ["Dhaka", "Chattogram", "Sylhet"],
    },
    maxActiveBeneficiaries: 300,
    monthlyFundCap: 8000000,
    totalAidedBeneficiaries: 1560,
    verified: true,
    status: "active",
    badges: ["zero-fraud", "quick-responder", "5-year-verified"],
    createdAt: "2014-08-20",
    lastActivityAt: "2024-06-15",
  },
  {
    id: "provider-5",
    organizationName: "Education for All Bangladesh",
    registrationType: "ngo",
    email: "contact@efabd.org",
    phone: "+880-1-9876-5432",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=EFA",
    description: "Dedicated to providing educational support and materials to underprivileged children.",
    registrationCertificate: "cert-567",
    bankStatement: "bank-stmt-567",
    officeAddressProof: "office-proof-567",
    portfolioImages: ["/school-students-classroom.jpg"],
    leadershipNIDCopies: ["nid-130"],
    references: [{ organizationName: "Ministry of Education", contactPerson: "Kamal", email: "kamal@moe.gov" }],
    trustScore: 72,
    completionRate: 88,
    averageRating: 4.1,
    responseTimeHours: 24,
    yearsActive: 6,
    fraudIncidents: 0,
    specialization: ["education", "poverty"],
    geographicFocus: {
      divisions: ["Rangpur", "Rajshahi", "Mymensingh"],
      districts: ["Dinajpur", "Rajshahi", "Mymensingh"],
    },
    maxActiveBeneficiaries: 150,
    monthlyFundCap: 3000000,
    totalAidedBeneficiaries: 650,
    verified: true,
    status: "active",
    badges: ["100-families"],
    createdAt: "2018-03-12",
    lastActivityAt: "2024-06-14",
  },
  {
    id: "provider-6",
    organizationName: "Rapid Response Team Dhaka",
    registrationType: "volunteer",
    email: "emergency@rrtdhaka.org",
    phone: "+880-1-5555-1234",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=RRT",
    description: "Emergency response team specializing in fire and disaster immediate relief.",
    registrationCertificate: "cert-890",
    bankStatement: "bank-stmt-890",
    officeAddressProof: "office-proof-890",
    portfolioImages: ["/placeholder-sbne4.png"],
    leadershipNIDCopies: ["nid-131", "nid-132"],
    references: [{ organizationName: "Fire Service", contactPerson: "Hasan", email: "hasan@fire.gov" }],
    trustScore: 65,
    completionRate: 82,
    averageRating: 4.0,
    responseTimeHours: 8,
    yearsActive: 4,
    fraudIncidents: 0,
    specialization: ["fire", "flood"],
    geographicFocus: {
      divisions: ["Dhaka"],
      districts: ["Dhaka", "Gazipur", "Narayanganj"],
    },
    maxActiveBeneficiaries: 100,
    monthlyFundCap: 2000000,
    totalAidedBeneficiaries: 340,
    verified: true,
    status: "active",
    badges: ["quick-responder"],
    createdAt: "2020-01-15",
    lastActivityAt: "2024-06-15",
  },
  // EDGE CASE: Provider on watchlist - suspicious rapid completions
  {
    id: "provider-7",
    organizationName: "Quick Aid Services",
    registrationType: "ngo",
    email: "info@quickaid.org",
    phone: "+880-1-3333-9999",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=QAS",
    description: "Fast-track relief distribution. Currently under review for unusually rapid case completions.",
    registrationCertificate: "cert-777",
    bankStatement: "bank-stmt-777",
    officeAddressProof: "office-proof-777",
    portfolioImages: ["/quick-distribution.jpg"],
    leadershipNIDCopies: ["nid-140", "nid-141"],
    references: [{ organizationName: "Local Chamber", contactPerson: "Rahim", email: "rahim@chamber.org" }],
    trustScore: 58,
    completionRate: 96,
    averageRating: 3.5,
    responseTimeHours: 2,
    yearsActive: 3,
    fraudIncidents: 1,
    specialization: ["poverty", "livelihood"],
    geographicFocus: {
      divisions: ["Chittagong", "Sylhet"],
      districts: ["Chattogram", "Cox's Bazar", "Sylhet"],
    },
    maxActiveBeneficiaries: 150,
    monthlyFundCap: 4000000,
    totalAidedBeneficiaries: 380,
    verified: true,
    status: "watchlist",
    badges: ["quick-responder"],
    createdAt: "2021-04-10",
    lastActivityAt: "2024-06-15",
  },
  // EDGE CASE: Provider at capacity - cannot accept new applications
  {
    id: "provider-8",
    organizationName: "Community Welfare Trust",
    registrationType: "ngo",
    email: "contact@cwt.org.bd",
    phone: "+880-2-7777-8888",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=CWT",
    description: "Currently serving maximum capacity of beneficiaries. New applications will be waitlisted.",
    registrationCertificate: "cert-888",
    bankStatement: "bank-stmt-888",
    officeAddressProof: "office-proof-888",
    portfolioImages: ["/community-work.jpg"],
    leadershipNIDCopies: ["nid-142"],
    references: [{ organizationName: "Social Welfare", contactPerson: "Nasrin", email: "nasrin@sw.gov.bd" }],
    trustScore: 82,
    completionRate: 91,
    averageRating: 4.4,
    responseTimeHours: 16,
    yearsActive: 7,
    fraudIncidents: 0,
    specialization: ["poverty", "education", "livelihood"],
    geographicFocus: {
      divisions: ["Barisal", "Khulna"],
      districts: ["Barisal", "Patuakhali", "Khulna"],
    },
    maxActiveBeneficiaries: 80,
    monthlyFundCap: 2500000,
    totalAidedBeneficiaries: 520,
    verified: true,
    status: "active",
    badges: ["100-families"],
    createdAt: "2017-11-22",
    lastActivityAt: "2024-06-14",
  },
  // EDGE CASE: New provider - low trust score, under probation
  {
    id: "provider-9",
    organizationName: "New Hope Initiative",
    registrationType: "volunteer",
    email: "info@newhope.bd",
    phone: "+880-1-2222-3333",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=NHI",
    description: "Newly established volunteer group. Building reputation through transparent operations.",
    registrationCertificate: "cert-999",
    bankStatement: "bank-stmt-999",
    officeAddressProof: "office-proof-999",
    portfolioImages: ["/new-team.jpg"],
    leadershipNIDCopies: ["nid-143"],
    references: [{ organizationName: "Local Council", contactPerson: "Jamal", email: "jamal@council.local" }],
    trustScore: 35,
    completionRate: 70,
    averageRating: 3.9,
    responseTimeHours: 36,
    yearsActive: 1,
    fraudIncidents: 0,
    specialization: ["poverty", "livelihood"],
    geographicFocus: {
      divisions: ["Mymensingh"],
      districts: ["Mymensingh", "Jamalpur"],
    },
    maxActiveBeneficiaries: 30,
    monthlyFundCap: 800000,
    totalAidedBeneficiaries: 45,
    verified: true,
    status: "active",
    badges: [],
    createdAt: "2023-05-15",
    lastActivityAt: "2024-06-13",
  },
  // EDGE CASE: Suspended provider - under investigation
  {
    id: "provider-suspicious-1",
    organizationName: "Relief First Network",
    registrationType: "ngo",
    email: "suspended@relieffirst.org",
    phone: "+880-1-1111-0000",
    profileImage: "https://api.dicebear.com/7.x/initials/svg?seed=RFN",
    description: "SUSPENDED: Multiple fraud alerts triggered. Distribution proofs under investigation.",
    registrationCertificate: "cert-suspended-1",
    bankStatement: "bank-stmt-suspended-1",
    officeAddressProof: "office-proof-suspended-1",
    portfolioImages: [],
    leadershipNIDCopies: ["nid-suspicious-1"],
    references: [],
    trustScore: 28,
    completionRate: 62,
    averageRating: 2.8,
    responseTimeHours: 72,
    yearsActive: 2,
    fraudIncidents: 3,
    specialization: ["flood", "poverty"],
    geographicFocus: {
      divisions: ["Rangpur"],
      districts: ["Rangpur", "Dinajpur"],
    },
    maxActiveBeneficiaries: 50,
    monthlyFundCap: 1500000,
    totalAidedBeneficiaries: 85,
    verified: false,
    status: "suspended",
    badges: [],
    createdAt: "2022-08-01",
    lastActivityAt: "2024-06-01",
  },
]

// Mock Beneficiaries
export const mockBeneficiaries: Beneficiary[] = [
  // EDGE CASE: Beneficiary with COMPLETED case from 2024 + NEW ONGOING case in 2025
  {
    id: "beneficiary-1",
    nidNumber: "1234567890123",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=amina",
    fullName: "Amina Begum",
    age: 32,
    phone: "+88017XXXXXXXX",
    address: "House 5, Village Kazipur, Satkhira Sadar",
    location: {
      division: "Khulna",
      district: "Satkhira",
      upazila: "Satkhira Sadar",
      coordinates: { lat: 22.35, lng: 89.08 },
    },
    needCategory: "medical",
    needDescription:
      "NEW EMERGENCY 2025: Son needs urgent medical treatment for dengue fever. High fever for 5 days. Previously received shelter aid in 2024 (completed).",
    amountRequested: 25000,
    urgencyLevel: "critical",
    itemizedBreakdown: [
      { item: "Hospital admission", cost: 15000 },
      { item: "Medicines and tests", cost: 7000 },
      { item: "Nursing care", cost: 3000 },
    ],
    crisisProofImages: ["/medical-emergency-2025.jpg", "/hospital-admission-letter.jpg"],
    familySize: 5,
    dependents: 3,
    dependentDetails: [
      { name: "Rahim (son - current patient)", age: 10 },
      { name: "Noor (daughter)", age: 8 },
      { name: "Ali (son)", age: 5 },
    ],
    incomeSources: ["Agriculture", "Day labor"],
    geographicPreference: "local",
    organizationSizePreference: "medium",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXX",
    applicationStatus: "verified",
    verificationStatus: "verified",
    privacyMode: "limited",
    allocatedProviderId: undefined,
    providerApplications: [
      // === PREVIOUS YEAR 2024 - COMPLETED CASE (Cyclone shelter aid) ===
      {
        providerId: "provider-1",
        status: "rejected",
        appliedDate: "2024-06-03",
        responseDate: "2024-06-04",
        rejectionReason: "Service area does not cover Satkhira at this time. We recommend applying to local organizations.",
      },
      {
        providerId: "provider-2",
        status: "completed",
        appliedDate: "2024-06-05",
        responseDate: "2024-06-07",
        completionDate: "2024-06-12",
        amountReceived: 20000,
        rating: 5,
        feedback: "LAST YEAR (2024): Excellent service for cyclone shelter aid, very quick and professional. They verified my family and delivered materials within 3 days.",
      },
      // === CURRENT YEAR 2025 - NEW MEDICAL EMERGENCY (Ongoing) ===
      {
        providerId: "provider-4",
        status: "applied",
        appliedDate: "2025-11-05",
      },
      {
        providerId: "provider-1",
        status: "applied",
        appliedDate: "2025-11-06",
      },
    ],
    providerRating: 5,
    providerFeedback:
      "Previous case (2024): Excellent service, very quick and professional. They verified my family and delivered materials within 3 days.",
    appliedDate: "2025-11-05",
    allocationDate: undefined,
    completionDate: undefined,
    impactStory:
      "Previous case (2024): With the building materials from this aid, we rebuilt our house roof. Our family now has shelter from the monsoon. Now facing new medical emergency in 2025.",
  },
  // EDGE CASE: Beneficiary with COMPLETED case in 2024 + CURRENT IN-PROGRESS case in 2025
  {
    id: "beneficiary-2",
    nidNumber: "9876543210987",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=mohammad",
    fullName: "Mohammad Karim",
    age: 45,
    phone: "+88018XXXXXXXX",
    address: "School Road, Sylhet Sadar",
    location: {
      division: "Sylhet",
      district: "Sylhet",
      upazila: "Sylhet Sadar",
      coordinates: { lat: 24.89, lng: 91.87 },
    },
    needCategory: "livelihood",
    needDescription:
      "NEW 2025: Lost small shop in recent fire. Need funds to restart business. Previously received education support in 2024 (completed successfully).",
    amountRequested: 35000,
    urgencyLevel: "high",
    itemizedBreakdown: [
      { item: "Shop rent advance", cost: 15000 },
      { item: "Initial inventory", cost: 15000 },
      { item: "Equipment and fixtures", cost: 5000 },
    ],
    crisisProofImages: ["/fire-damage-shop.jpg", "/shop-rental-agreement.jpg"],
    familySize: 6,
    dependents: 4,
    dependentDetails: [
      { name: "Sajid (son)", age: 15, education: "School" },
      { name: "Sara (daughter)", age: 12, education: "School" },
      { name: "Hasan (son)", age: 8, education: "School" },
      { name: "Leila (daughter)", age: 5, education: "Pre-school" },
    ],
    incomeSources: ["Small business - Shop (currently destroyed by fire)"],
    organizationSizePreference: "medium",
    geographicPreference: "local",
    paymentMethod: "bank",
    accountNumber: "XXX-XXXX-XXXX-XXXX",
    applicationStatus: "in-progress",
    verificationStatus: "verified",
    privacyMode: "anonymous",
    appliedDate: "2025-11-03",
    allocatedProviderId: "provider-3",
    allocationDate: "2025-11-05",
    providerApplications: [
      // === PREVIOUS YEAR 2024 - COMPLETED EDUCATION SUPPORT ===
      {
        providerId: "provider-5",
        status: "completed",
        appliedDate: "2024-04-10",
        responseDate: "2024-04-12",
        completionDate: "2024-04-20",
        amountReceived: 5000,
        rating: 5,
        feedback: "PREVIOUS CASE 2024: Received education support for children's school fees. Very satisfied with the service!",
      },
      // === CURRENT YEAR 2025 - NEW LIVELIHOOD SUPPORT (In Progress) ===
      {
        providerId: "provider-1",
        status: "rejected",
        appliedDate: "2025-11-01",
        responseDate: "2025-11-02",
        rejectionReason: "We don't cover livelihood sector currently. Focus is on emergency relief only.",
      },
      {
        providerId: "provider-3",
        status: "in-progress",
        appliedDate: "2025-11-03",
        responseDate: "2025-11-05",
      },
      {
        providerId: "provider-2",
        status: "applied",
        appliedDate: "2025-11-04",
      },
    ],
  },
  {
    id: "beneficiary-3",
    nidNumber: "5555555555555",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=fatima",
    fullName: "Fatima Khatun",
    age: 68,
    phone: "+88019XXXXXXXX",
    address: "Old Town, Sylhet Sadar",
    location: {
      division: "Sylhet",
      district: "Sylhet",
      upazila: "Sylhet Sadar",
      coordinates: { lat: 24.9, lng: 91.86 },
    },
    needCategory: "food",
    needDescription: "Elderly widow struggling with food security. Son cannot support adequately. Winter approaching.",
    amountRequested: 3000,
    urgencyLevel: "high",
    itemizedBreakdown: [
      { item: "Rice (20kg)", cost: 1000 },
      { item: "Lentils and pulses", cost: 800 },
      { item: "Cooking oil and salt", cost: 600 },
      { item: "Blankets for winter", cost: 600 },
    ],
    crisisProofImages: ["/elderly-home.jpg"],
    familySize: 1,
    dependents: 0,
    dependentDetails: [],
    incomeSources: ["Widow pension - 2000 BDT/month"],
    organizationSizePreference: "small",
    geographicPreference: "local",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXY",
    applicationStatus: "matched",
    verificationStatus: "verified",
    privacyMode: "limited",
    appliedDate: "2024-06-14",
    allocatedProviderId: "provider-3",
    allocationDate: "2024-06-15",
    providerApplications: [
      {
        providerId: "provider-3",
        status: "accepted",
        appliedDate: "2024-06-14",
        responseDate: "2024-06-15",
      },
      {
        providerId: "provider-1",
        status: "rejected",
        appliedDate: "2024-06-13",
        responseDate: "2024-06-14",
        rejectionReason: "Currently prioritizing flood-affected families. Your case doesn't match current crisis focus.",
      },
    ],
  },
  {
    id: "beneficiary-4",
    nidNumber: "1111222233334",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=rahman",
    fullName: "Abdul Rahman",
    age: 38,
    phone: "+88016XXXXXXXX",
    address: "Village Rampur, Sunamganj Sadar",
    location: {
      division: "Sylhet",
      district: "Sunamganj",
      upazila: "Sunamganj Sadar",
      coordinates: { lat: 25.07, lng: 91.39 },
    },
    needCategory: "livelihood",
    needDescription: "Lost fishing boat and nets in flood. Need equipment to restart livelihood.",
    amountRequested: 15000,
    urgencyLevel: "emergency",
    itemizedBreakdown: [
      { item: "Fishing nets", cost: 8000 },
      { item: "Boat repair materials", cost: 5000 },
      { item: "Fishing equipment", cost: 2000 },
    ],
    crisisProofImages: ["/placeholder-sbne4.png"],
    familySize: 7,
    dependents: 5,
    dependentDetails: [{ name: "Children (5)", age: 12 }],
    incomeSources: ["Fishing (currently unable)"],
    geographicPreference: "local",
    organizationSizePreference: "medium",
    paymentMethod: "nagad",
    accountNumber: "01XXXXXXXXZ",
    applicationStatus: "completed",
    verificationStatus: "verified",
    privacyMode: "full",
    appliedDate: "2024-06-08",
    allocatedProviderId: "provider-3",
    allocationDate: "2024-06-09",
    completionDate: "2024-06-14",
    providerRating: 4,
    providerFeedback: "Good service, but took a bit longer than expected. Overall satisfied.",
    impactStory: "Received new fishing nets and repaired my boat. Back to fishing and earning for my family.",
    providerApplications: [
      {
        providerId: "provider-3",
        status: "completed",
        appliedDate: "2024-06-08",
        responseDate: "2024-06-09",
        amountReceived: 15000,
        rating: 4,
        feedback: "Good service, but took a bit longer than expected. Overall satisfied.",
      },
      {
        providerId: "provider-5",
        status: "completed",
        appliedDate: "2024-05-20",
        responseDate: "2024-05-22",
        amountReceived: 8000,
        rating: 5,
        feedback: "Excellent support! Very fast response and kind staff.",
      },
    ],
  },
  {
    id: "beneficiary-5",
    nidNumber: "7777888899990",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=nasrin",
    fullName: "Nasrin Akter",
    age: 28,
    phone: "+88015XXXXXXXX",
    address: "Medical Road, Sylhet City",
    location: {
      division: "Sylhet",
      district: "Sylhet",
      upazila: "Sylhet Sadar",
      coordinates: { lat: 24.91, lng: 91.88 },
    },
    needCategory: "medical",
    needDescription: "Daughter needs urgent surgery. Cannot afford hospital fees.",
    amountRequested: 25000,
    urgencyLevel: "critical",
    itemizedBreakdown: [
      { item: "Surgery fees", cost: 18000 },
      { item: "Medicines", cost: 5000 },
      { item: "Hospital stay", cost: 2000 },
    ],
    crisisProofImages: ["/medical-facility.jpg"],
    familySize: 4,
    dependents: 2,
    dependentDetails: [
      { name: "Ayesha (daughter)", age: 6, education: "Requires surgery" },
      { name: "Rafi (son)", age: 3 },
    ],
    incomeSources: ["Garment worker - 8000 BDT/month"],
    geographicPreference: "national",
    organizationSizePreference: "large",
    paymentMethod: "bank",
    accountNumber: "XXX-YYYY-ZZZZ",
    applicationStatus: "in-progress",
    verificationStatus: "verified",
    privacyMode: "limited",
    appliedDate: "2024-06-12",
    allocatedProviderId: "provider-4",
    allocationDate: "2024-06-13",
    providerApplications: [
      {
        providerId: "provider-4",
        status: "in-progress",
        appliedDate: "2024-06-12",
        responseDate: "2024-06-13",
      },
      {
        providerId: "provider-1",
        status: "applied",
        appliedDate: "2024-06-11",
      },
      {
        providerId: "provider-2",
        status: "applied",
        appliedDate: "2024-06-10",
      },
    ],
  },
  {
    id: "beneficiary-6",
    nidNumber: "4444555566667",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=habib",
    fullName: "Habibullah Mia",
    age: 52,
    phone: "+88014XXXXXXXX",
    address: "Char Area, Sunamganj",
    location: {
      division: "Sylhet",
      district: "Sunamganj",
      upazila: "Tahirpur",
      coordinates: { lat: 25.03, lng: 91.42 },
    },
    needCategory: "food",
    needDescription: "Flood destroyed crops. Family has no food for next 2 months.",
    amountRequested: 8000,
    urgencyLevel: "emergency",
    itemizedBreakdown: [
      { item: "Rice (50kg)", cost: 2500 },
      { item: "Lentils and vegetables", cost: 2000 },
      { item: "Cooking oil and spices", cost: 1500 },
      { item: "Emergency supplies", cost: 2000 },
    ],
    crisisProofImages: ["/placeholder-sbne4.png"],
    familySize: 8,
    dependents: 6,
    dependentDetails: [{ name: "Family members", age: 0 }],
    incomeSources: ["Farmer (crops destroyed)"],
    geographicPreference: "local",
    organizationSizePreference: "small",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXA",
    applicationStatus: "verified",
    verificationStatus: "verified",
    privacyMode: "anonymous",
    appliedDate: "2024-06-13",
  },
  {
    id: "beneficiary-7",
    nidNumber: "2222333344445",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=sultana",
    fullName: "Sultana Begum",
    age: 35,
    phone: "+88013XXXXXXXX",
    address: "Korail Slum, Dhaka",
    location: {
      division: "Dhaka",
      district: "Dhaka",
      upazila: "Gulshan",
      coordinates: { lat: 23.79, lng: 90.41 },
    },
    needCategory: "shelter",
    needDescription: "Lost home in slum fire. Need temporary shelter materials urgently.",
    amountRequested: 12000,
    urgencyLevel: "critical",
    itemizedBreakdown: [
      { item: "Tarpaulin sheets", cost: 4000 },
      { item: "Bamboo poles", cost: 3000 },
      { item: "Rope and nails", cost: 2000 },
      { item: "Emergency supplies", cost: 3000 },
    ],
    crisisProofImages: ["/placeholder-sbne4.png"],
    familySize: 4,
    dependents: 2,
    dependentDetails: [
      { name: "Mina (daughter)", age: 7 },
      { name: "Rahim (son)", age: 4 },
    ],
    incomeSources: ["Domestic worker - 6000 BDT/month"],
    geographicPreference: "local",
    organizationSizePreference: "medium",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXB",
    applicationStatus: "matched",
    verificationStatus: "verified",
    privacyMode: "limited",
    appliedDate: "2024-06-14",
    allocatedProviderId: "provider-6",
    allocationDate: "2024-06-15",
  },
  {
    id: "beneficiary-8",
    nidNumber: "8888999900001",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=jalal",
    fullName: "Jalal Uddin",
    age: 42,
    phone: "+88012XXXXXXXX",
    address: "Village Paba, Rajshahi",
    location: {
      division: "Rajshahi",
      district: "Rajshahi",
      upazila: "Paba",
      coordinates: { lat: 24.37, lng: 88.6 },
    },
    needCategory: "livelihood",
    needDescription: "Drought destroyed entire crop. Need seeds and irrigation support for next season.",
    amountRequested: 18000,
    urgencyLevel: "high",
    itemizedBreakdown: [
      { item: "Seeds (rice, vegetables)", cost: 8000 },
      { item: "Fertilizer", cost: 5000 },
      { item: "Irrigation equipment", cost: 5000 },
    ],
    crisisProofImages: ["/placeholder-sbne4.png"],
    familySize: 6,
    dependents: 4,
    dependentDetails: [{ name: "Children (4)", age: 10 }],
    incomeSources: ["Farming (currently no income)"],
    geographicPreference: "local",
    organizationSizePreference: "medium",
    paymentMethod: "nagad",
    accountNumber: "01XXXXXXXXC",
    applicationStatus: "pending",
    verificationStatus: "under-review",
    privacyMode: "full",
    appliedDate: "2024-06-15",
  },
  // EDGE CASE: Multiple rejections before getting accepted
  {
    id: "beneficiary-9",
    nidNumber: "3333444455556",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=rohima",
    fullName: "Rohima Akter",
    age: 29,
    phone: "+88011XXXXXXXX",
    address: "Village Char Rampur, Noakhali",
    location: {
      division: "Chittagong",
      district: "Noakhali",
      upazila: "Noakhali Sadar",
      coordinates: { lat: 22.87, lng: 91.1 },
    },
    needCategory: "shelter",
    needDescription: "Riverbank erosion destroyed home. Family displaced for 3 months. Need emergency shelter.",
    amountRequested: 22000,
    urgencyLevel: "critical",
    itemizedBreakdown: [
      { item: "Tin sheets (CGI)", cost: 10000 },
      { item: "Bamboo and wood", cost: 7000 },
      { item: "Construction materials", cost: 5000 },
    ],
    crisisProofImages: ["/erosion-damage.jpg", "/displaced-family.jpg"],
    familySize: 6,
    dependents: 4,
    dependentDetails: [
      { name: "Sadia (daughter)", age: 12 },
      { name: "Kamal (son)", age: 9 },
      { name: "Mim (daughter)", age: 6 },
      { name: "Baby", age: 1 },
    ],
    incomeSources: ["Day labor - irregular income"],
    geographicPreference: "local",
    organizationSizePreference: "medium",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXD",
    applicationStatus: "in-progress",
    verificationStatus: "verified",
    privacyMode: "limited",
    appliedDate: "2024-05-25",
    allocatedProviderId: "provider-2",
    allocationDate: "2024-06-10",
    providerApplications: [
      {
        providerId: "provider-1",
        status: "rejected",
        appliedDate: "2024-05-25",
        responseDate: "2024-05-27",
        rejectionReason: "Geographic area not covered. We operate only in Sylhet division at this time.",
      },
      {
        providerId: "provider-4",
        status: "rejected",
        appliedDate: "2024-05-28",
        responseDate: "2024-05-30",
        rejectionReason: "We specialize in medical emergencies only. Cannot fulfill shelter needs.",
      },
      {
        providerId: "provider-6",
        status: "rejected",
        appliedDate: "2024-06-01",
        responseDate: "2024-06-02",
        rejectionReason: "Currently at maximum capacity (150/150 active cases). Please reapply in 2 weeks.",
      },
      {
        providerId: "provider-3",
        status: "rejected",
        appliedDate: "2024-06-05",
        responseDate: "2024-06-06",
        rejectionReason: "Budget exhausted for this month. Applications reopening next month.",
      },
      {
        providerId: "provider-2",
        status: "accepted",
        appliedDate: "2024-06-08",
        responseDate: "2024-06-10",
      },
    ],
  },
  // EDGE CASE: Verification failed initially, resubmitted with corrections
  {
    id: "beneficiary-10",
    nidNumber: "6677889900112",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=firoz",
    fullName: "Firoz Ahmed",
    age: 51,
    phone: "+88010XXXXXXXX",
    address: "Jhikargacha, Jessore",
    location: {
      division: "Khulna",
      district: "Jessore",
      upazila: "Jhikargacha",
      coordinates: { lat: 23.1, lng: 89.1 },
    },
    needCategory: "medical",
    needDescription: "Wife requires emergency kidney treatment. Previously submitted incomplete documents, now resubmitted.",
    amountRequested: 45000,
    urgencyLevel: "critical",
    itemizedBreakdown: [
      { item: "Dialysis sessions (10)", cost: 25000 },
      { item: "Medications", cost: 12000 },
      { item: "Doctor consultations", cost: 8000 },
    ],
    crisisProofImages: ["/medical-reports-updated.jpg", "/hospital-bills.jpg", "/doctor-prescription.jpg"],
    familySize: 5,
    dependents: 3,
    dependentDetails: [
      { name: "Salma (wife - patient)", age: 48 },
      { name: "Rony (son)", age: 22 },
      { name: "Mili (daughter)", age: 18 },
    ],
    incomeSources: ["Small shop - 12000 BDT/month"],
    geographicPreference: "national",
    organizationSizePreference: "large",
    paymentMethod: "bank",
    accountNumber: "XXX-BANK-9876",
    applicationStatus: "verified",
    verificationStatus: "verified",
    privacyMode: "limited",
    appliedDate: "2024-06-14",
    providerApplications: [
      {
        providerId: "provider-4",
        status: "applied",
        appliedDate: "2024-06-14",
      },
      {
        providerId: "provider-1",
        status: "applied",
        appliedDate: "2024-06-13",
      },
    ],
  },
  // EDGE CASE: Received partial help from multiple providers
  {
    id: "beneficiary-11",
    nidNumber: "1122334455667",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=taslima",
    fullName: "Taslima Begum",
    age: 34,
    phone: "+88009XXXXXXXX",
    address: "Monirampur, Jessore",
    location: {
      division: "Khulna",
      district: "Jessore",
      upazila: "Monirampur",
      coordinates: { lat: 23.2, lng: 89.2 },
    },
    needCategory: "education",
    needDescription: "Three children need school fees and supplies. Total needed 30K but receiving partial help from 3 providers.",
    amountRequested: 30000,
    urgencyLevel: "high",
    itemizedBreakdown: [
      { item: "School fees (3 children)", cost: 18000 },
      { item: "Books and supplies", cost: 8000 },
      { item: "Uniforms and shoes", cost: 4000 },
    ],
    crisisProofImages: ["/school-admission-letters.jpg"],
    familySize: 5,
    dependents: 3,
    dependentDetails: [
      { name: "Sakib (son)", age: 14, education: "Class 9" },
      { name: "Sanjida (daughter)", age: 11, education: "Class 6" },
      { name: "Samin (son)", age: 8, education: "Class 3" },
    ],
    incomeSources: ["Tailoring - 8000 BDT/month"],
    geographicPreference: "national",
    organizationSizePreference: "medium",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXE",
    applicationStatus: "completed",
    verificationStatus: "verified",
    privacyMode: "full",
    appliedDate: "2024-05-20",
    providerApplications: [
      {
        providerId: "provider-5",
        status: "completed",
        appliedDate: "2024-05-20",
        responseDate: "2024-05-22",
        completionDate: "2024-05-28",
        amountReceived: 10000,
        rating: 5,
        feedback: "Covered school fees for 2 children. Very helpful!",
      },
      {
        providerId: "provider-3",
        status: "completed",
        appliedDate: "2024-05-25",
        responseDate: "2024-05-27",
        completionDate: "2024-06-02",
        amountReceived: 8000,
        rating: 4,
        feedback: "Provided books and supplies. Good service.",
      },
      {
        providerId: "provider-1",
        status: "completed",
        appliedDate: "2024-06-01",
        responseDate: "2024-06-03",
        completionDate: "2024-06-08",
        amountReceived: 6000,
        rating: 5,
        feedback: "Covered uniforms for all 3 children. Excellent!",
      },
      {
        providerId: "provider-2",
        status: "rejected",
        appliedDate: "2024-05-18",
        responseDate: "2024-05-19",
        rejectionReason: "We don't cover education sector. Focus is on emergency relief only.",
      },
    ],
    completionDate: "2024-06-08",
    providerRating: 5,
    impactStory: "All three of my children are now going to school regularly thanks to the combined support!",
  },
  // EDGE CASE: Application rejected due to fraud suspicion
  {
    id: "beneficiary-12",
    nidNumber: "9988776655443",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=suspicious",
    fullName: "Kamal Hossain",
    age: 35,
    phone: "+88008XXXXXXXX",
    address: "Mirpur, Dhaka",
    location: {
      division: "Dhaka",
      district: "Dhaka",
      upazila: "Mirpur",
      coordinates: { lat: 23.8, lng: 90.36 },
    },
    needCategory: "shelter",
    needDescription: "Lost home in fire incident. Need immediate shelter assistance.",
    amountRequested: 50000,
    urgencyLevel: "critical",
    itemizedBreakdown: [
      { item: "Tin sheets", cost: 30000 },
      { item: "Construction", cost: 20000 },
    ],
    crisisProofImages: ["/fire-damage-suspicious.jpg"],
    familySize: 4,
    dependents: 2,
    dependentDetails: [{ name: "Children (2)", age: 10 }],
    incomeSources: ["Business - claimed"],
    geographicPreference: "local",
    organizationSizePreference: "large",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXF",
    applicationStatus: "rejected",
    verificationStatus: "rejected",
    privacyMode: "anonymous",
    appliedDate: "2024-06-10",
    rejectionReason: "AI verification detected inconsistencies: GPS mismatch in photos, duplicate NID usage detected in system, image metadata shows editing. Please contact admin for clarification.",
    providerApplications: [
      {
        providerId: "provider-1",
        status: "rejected",
        appliedDate: "2024-06-10",
        responseDate: "2024-06-11",
        rejectionReason: "Failed AI verification - suspicious documents detected.",
      },
      {
        providerId: "provider-6",
        status: "rejected",
        appliedDate: "2024-06-12",
        responseDate: "2024-06-12",
        rejectionReason: "Red flag from fraud detection system. Application under investigation.",
      },
    ],
  },
  // EDGE CASE: Pending applications with 5 different providers
  {
    id: "beneficiary-13",
    nidNumber: "2244668800113",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=rahela",
    fullName: "Rahela Khatun",
    age: 41,
    phone: "+88007XXXXXXXX",
    address: "Char Fasson, Bhola",
    location: {
      division: "Barisal",
      district: "Bhola",
      upazila: "Char Fasson",
      coordinates: { lat: 22.3, lng: 90.73 },
    },
    needCategory: "food",
    needDescription: "Cyclone destroyed crops and food storage. Family of 9 has no food. Applied to multiple providers for urgent help.",
    amountRequested: 15000,
    urgencyLevel: "emergency",
    itemizedBreakdown: [
      { item: "Rice (100kg)", cost: 5000 },
      { item: "Lentils and oil", cost: 4000 },
      { item: "Vegetables and protein", cost: 3000 },
      { item: "Emergency rations", cost: 3000 },
    ],
    crisisProofImages: ["/cyclone-damage-char.jpg", "/empty-storage.jpg"],
    familySize: 9,
    dependents: 7,
    dependentDetails: [
      { name: "Elderly mother", age: 72 },
      { name: "Children (5)", age: 8 },
      { name: "Disabled brother", age: 38 },
    ],
    incomeSources: ["Farming - completely destroyed"],
    geographicPreference: "national",
    organizationSizePreference: "medium",
    paymentMethod: "bkash",
    accountNumber: "01XXXXXXXXG",
    applicationStatus: "verified",
    verificationStatus: "verified",
    privacyMode: "limited",
    appliedDate: "2024-06-12",
    providerApplications: [
      {
        providerId: "provider-1",
        status: "applied",
        appliedDate: "2024-06-12",
      },
      {
        providerId: "provider-2",
        status: "applied",
        appliedDate: "2024-06-13",
      },
      {
        providerId: "provider-3",
        status: "applied",
        appliedDate: "2024-06-14",
      },
      {
        providerId: "provider-4",
        status: "rejected",
        appliedDate: "2024-06-13",
        responseDate: "2024-06-13",
        rejectionReason: "Medical-only provider. Cannot assist with food needs.",
      },
      {
        providerId: "provider-5",
        status: "applied",
        appliedDate: "2024-06-15",
      },
    ],
  },
  // EDGE CASE: Slow progress - stuck in verification for long time
  {
    id: "beneficiary-14",
    nidNumber: "5566778899001",
    nidFrontImage: "/nid-front-blurry.jpg",
    nidBackImage: "/nid-back-incomplete.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=delayed",
    fullName: "Monir Uddin",
    age: 58,
    phone: "+88006XXXXXXXX",
    address: "Remote Haor Area, Kishoreganj",
    location: {
      division: "Dhaka",
      district: "Kishoreganj",
      upazila: "Mithamain",
      coordinates: { lat: 24.7, lng: 90.95 },
    },
    needCategory: "livelihood",
    needDescription: "Boat sank in storm. Lost fishing equipment worth 35K. Need help to restart livelihood.",
    amountRequested: 35000,
    urgencyLevel: "high",
    itemizedBreakdown: [
      { item: "New fishing boat", cost: 25000 },
      { item: "Fishing nets", cost: 8000 },
      { item: "Equipment", cost: 2000 },
    ],
    crisisProofImages: ["/storm-damage-low-quality.jpg"],
    familySize: 8,
    dependents: 6,
    dependentDetails: [{ name: "Large family", age: 0 }],
    incomeSources: ["Fishing - currently unable"],
    geographicPreference: "local",
    organizationSizePreference: "small",
    paymentMethod: "nagad",
    accountNumber: "01XXXXXXXXH",
    applicationStatus: "submitted",
    verificationStatus: "under-review",
    privacyMode: "full",
    appliedDate: "2024-05-15",
    providerApplications: [],
  },
  // EDGE CASE: Successfully completed with one provider, new emergency with another
  {
    id: "beneficiary-15",
    nidNumber: "7788990011223",
    nidFrontImage: "/nid-front.jpg",
    nidBackImage: "/nid-back.jpg",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=repeat",
    fullName: "Shahana Parvin",
    age: 30,
    phone: "+88005XXXXXXXX",
    address: "Companiganj, Sylhet",
    location: {
      division: "Sylhet",
      district: "Sylhet",
      upazila: "Companiganj",
      coordinates: { lat: 24.7, lng: 91.9 },
    },
    needCategory: "medical",
    needDescription: "Son recovered from surgery (prev completed case). Now daughter needs emergency treatment.",
    amountRequested: 28000,
    urgencyLevel: "emergency",
    itemizedBreakdown: [
      { item: "Surgery fees", cost: 20000 },
      { item: "Medicines", cost: 6000 },
      { item: "Hospital stay", cost: 2000 },
    ],
    crisisProofImages: ["/medical-emergency-new.jpg", "/hospital-admission.jpg"],
    familySize: 5,
    dependents: 3,
    dependentDetails: [
      { name: "Rashed (son - previous patient)", age: 12 },
      { name: "Ruhi (daughter - current patient)", age: 8 },
      { name: "Baby", age: 2 },
    ],
    incomeSources: ["Husband - day labor 10000 BDT/month"],
    geographicPreference: "local",
    organizationSizePreference: "large",
    paymentMethod: "bank",
    accountNumber: "XXX-BANK-5432",
    applicationStatus: "in-progress",
    verificationStatus: "verified",
    privacyMode: "limited",
    appliedDate: "2024-06-13",
    allocatedProviderId: "provider-4",
    allocationDate: "2024-06-14",
    providerApplications: [
      {
        providerId: "provider-4",
        status: "in-progress",
        appliedDate: "2024-06-13",
        responseDate: "2024-06-14",
      },
      {
        providerId: "provider-1",
        status: "completed",
        appliedDate: "2024-04-10",
        responseDate: "2024-04-12",
        completionDate: "2024-04-25",
        amountReceived: 15000,
        rating: 5,
        feedback: "Previous case: Son's surgery was successful. Very grateful!",
      },
    ],
  },
]

// Mock Donations - EXPANDED
export const mockDonations: Donation[] = [
  {
    id: "donation-1",
    donorId: "donor-1",
    crisisId: "crisis-1",
    amount: 10000,
    message: "Hope this helps the flood victims. Stay strong!",
    status: "completed",
    providerPreference: {
      positive: ["provider-1"],
      negative: [],
      geographicFocus: "Sylhet",
    },
    allocations: [
      {
        id: "alloc-1",
        donationId: "donation-1",
        beneficiaryId: "beneficiary-1",
        providerId: "provider-1",
        allocatedAmount: 10000,
        status: "completed",
        createdAt: "2024-06-07",
      },
    ],
    createdAt: "2024-06-06",
    refundSettings: {
      autoRefund: true,
      refundDays: 60,
    },
    transactionFee: 250,
  },
  {
    id: "donation-2",
    donorId: "donor-1",
    crisisId: "crisis-2",
    amount: 25000,
    message: "For cyclone victims. Praying for quick recovery.",
    status: "in-progress",
    providerPreference: {
      positive: ["provider-2"],
      negative: [],
      geographicFocus: "Khulna",
    },
    allocations: [
      {
        id: "alloc-2",
        donationId: "donation-2",
        beneficiaryId: "beneficiary-2",
        providerId: "provider-2",
        allocatedAmount: 25000,
        status: "in-progress",
        createdAt: "2024-06-10",
      },
    ],
    createdAt: "2024-06-09",
    refundSettings: {
      autoRefund: true,
      refundDays: 90,
    },
    transactionFee: 625,
  },
  {
    id: "donation-3",
    donorId: "donor-1",
    crisisId: "crisis-3",
    amount: 5000,
    message: "For medical treatment. Every life matters.",
    status: "verified",
    providerPreference: {
      positive: [],
      negative: [],
      geographicFocus: "Dhaka",
    },
    allocations: [
      {
        id: "alloc-3",
        donationId: "donation-3",
        beneficiaryId: "beneficiary-5",
        providerId: "provider-4",
        allocatedAmount: 5000,
        status: "verified",
        createdAt: "2024-06-11",
      },
    ],
    createdAt: "2024-06-11",
    refundSettings: {
      autoRefund: false,
    },
    transactionFee: 125,
  },
  {
    id: "donation-4",
    donorId: "donor-2",
    crisisId: "crisis-1",
    amount: 15000,
    message: "Supporting Sylhet flood relief efforts.",
    status: "completed",
    providerPreference: {
      positive: [],
      negative: [],
      geographicFocus: "Sylhet",
    },
    allocations: [
      {
        id: "alloc-4",
        donationId: "donation-4",
        beneficiaryId: "beneficiary-4",
        providerId: "provider-3",
        allocatedAmount: 15000,
        status: "completed",
        createdAt: "2024-06-09",
      },
    ],
    createdAt: "2024-06-08",
    refundSettings: {
      autoRefund: true,
      refundDays: 60,
    },
    transactionFee: 375,
  },
  {
    id: "donation-5",
    donorId: "donor-2",
    crisisId: "crisis-4",
    amount: 8000,
    message: "Education is the key to breaking poverty. Supporting students.",
    status: "in-progress",
    providerPreference: {
      positive: ["provider-5"],
      negative: [],
      crisisTypeFilter: ["education"],
    },
    allocations: [
      {
        id: "alloc-5",
        donationId: "donation-5",
        beneficiaryId: "beneficiary-2",
        providerId: "provider-3",
        allocatedAmount: 5000,
        status: "in-progress",
        createdAt: "2024-06-12",
      },
    ],
    createdAt: "2024-06-11",
    refundSettings: {
      autoRefund: true,
      refundDays: 90,
    },
    transactionFee: 200,
  },
  {
    id: "donation-6",
    donorId: "donor-3",
    crisisId: "crisis-6",
    amount: 30000,
    message: "Urgent help for fire victims. May Allah help them.",
    status: "provider-accepted",
    providerPreference: {
      positive: ["provider-6"],
      negative: [],
      geographicFocus: "Dhaka",
    },
    allocations: [
      {
        id: "alloc-6",
        donationId: "donation-6",
        beneficiaryId: "beneficiary-7",
        providerId: "provider-6",
        allocatedAmount: 12000,
        status: "provider-accepted",
        createdAt: "2024-06-15",
      },
    ],
    createdAt: "2024-06-14",
    refundSettings: {
      autoRefund: true,
      refundDays: 30,
    },
    transactionFee: 750,
  },
  {
    id: "donation-7",
    donorId: "donor-3",
    crisisId: "crisis-5",
    amount: 12000,
    message: "Winter blankets for vulnerable families.",
    status: "pending",
    providerPreference: {
      positive: [],
      negative: [],
      geographicFocus: "Mymensingh",
    },
    allocations: [],
    createdAt: "2024-06-15",
    refundSettings: {
      autoRefund: true,
      refundDays: 60,
    },
    transactionFee: 300,
  },
  {
    id: "donation-8",
    donorId: "donor-4",
    crisisId: "crisis-2",
    amount: 20000,
    message: "Helping cyclone-affected families rebuild their lives.",
    status: "completed",
    providerPreference: {
      positive: ["provider-2"],
      negative: [],
    },
    allocations: [
      {
        id: "alloc-7",
        donationId: "donation-8",
        beneficiaryId: "beneficiary-1",
        providerId: "provider-2",
        allocatedAmount: 20000,
        status: "completed",
        createdAt: "2024-06-07",
      },
    ],
    createdAt: "2024-06-06",
    refundSettings: {
      autoRefund: false,
    },
    transactionFee: 500,
  },
  {
    id: "donation-9",
    donorId: "donor-4",
    crisisId: "crisis-3",
    amount: 10000,
    message: "Medical emergency fund. Hope for quick recovery.",
    status: "in-progress",
    providerPreference: {
      positive: ["provider-4"],
      negative: [],
      crisisTypeFilter: ["medical"],
    },
    allocations: [
      {
        id: "alloc-8",
        donationId: "donation-9",
        beneficiaryId: "beneficiary-5",
        providerId: "provider-4",
        allocatedAmount: 10000,
        status: "in-progress",
        createdAt: "2024-06-13",
      },
    ],
    createdAt: "2024-06-12",
    refundSettings: {
      autoRefund: true,
      refundDays: 45,
    },
    transactionFee: 250,
  },
  {
    id: "donation-10",
    donorId: "donor-5",
    crisisId: "crisis-8",
    amount: 18000,
    message: "Supporting farmers affected by drought.",
    status: "pending",
    providerPreference: {
      positive: [],
      negative: [],
      geographicFocus: "Rajshahi",
      crisisTypeFilter: ["livelihood"],
    },
    allocations: [],
    createdAt: "2024-06-15",
    refundSettings: {
      autoRefund: true,
      refundDays: 60,
    },
    transactionFee: 450,
  },
  // EDGE CASE: Donation refunded due to unmet matching criteria
  {
    id: "donation-11",
    donorId: "donor-1",
    crisisId: "crisis-1",
    amount: 50000,
    message: "Large donation with strict provider requirements - must be verified NGO with 95+ trust score.",
    status: "refunded",
    providerPreference: {
      positive: [],
      negative: ["provider-suspicious-1", "provider-suspicious-2"],
      geographicFocus: "Sylhet",
    },
    allocations: [],
    createdAt: "2024-05-01",
    refundSettings: {
      autoRefund: true,
      refundDays: 30,
    },
    transactionFee: 1250,
  },
  // EDGE CASE: Partial allocation - donor specified split
  {
    id: "donation-12",
    donorId: "donor-2",
    crisisId: "crisis-2",
    amount: 60000,
    message: "Split donation for 3 beneficiaries - 20K each for cyclone victims.",
    status: "in-progress",
    providerPreference: {
      positive: ["provider-2", "provider-3"],
      negative: [],
      geographicFocus: "Khulna",
    },
    allocations: [
      {
        id: "alloc-12a",
        donationId: "donation-12",
        beneficiaryId: "beneficiary-1",
        providerId: "provider-2",
        allocatedAmount: 20000,
        status: "completed",
        createdAt: "2024-06-10",
      },
      {
        id: "alloc-12b",
        donationId: "donation-12",
        beneficiaryId: "beneficiary-9",
        providerId: "provider-2",
        allocatedAmount: 20000,
        status: "in-progress",
        createdAt: "2024-06-12",
      },
      {
        id: "alloc-12c",
        donationId: "donation-12",
        beneficiaryId: "beneficiary-7",
        providerId: "provider-6",
        allocatedAmount: 20000,
        status: "provider-accepted",
        createdAt: "2024-06-14",
      },
    ],
    createdAt: "2024-06-09",
    refundSettings: {
      autoRefund: true,
      refundDays: 90,
    },
    transactionFee: 1500,
  },
  // EDGE CASE: Stuck in matching - no suitable provider found
  {
    id: "donation-13",
    donorId: "donor-3",
    crisisId: "crisis-4",
    amount: 25000,
    message: "Very specific: Only for female education in remote haor areas, must have local presence.",
    status: "pending",
    providerPreference: {
      positive: [],
      negative: ["provider-1", "provider-4", "provider-6"],
      geographicFocus: "Sylhet",
      crisisTypeFilter: ["education"],
    },
    allocations: [],
    createdAt: "2024-06-01",
    refundSettings: {
      autoRefund: true,
      refundDays: 45,
    },
    transactionFee: 625,
  },
  // EDGE CASE: Disputed distribution - potential fraud flagged
  {
    id: "donation-14",
    donorId: "donor-4",
    crisisId: "crisis-6",
    amount: 35000,
    message: "Fire relief support - expecting verified distribution proof.",
    status: "in-progress",
    providerPreference: {
      positive: ["provider-6"],
      negative: [],
    },
    allocations: [
      {
        id: "alloc-suspicious-1",
        donationId: "donation-14",
        beneficiaryId: "beneficiary-7",
        providerId: "provider-6",
        allocatedAmount: 35000,
        status: "in-progress",
        createdAt: "2024-06-15",
      },
    ],
    createdAt: "2024-06-14",
    refundSettings: {
      autoRefund: true,
      refundDays: 60,
    },
    transactionFee: 875,
  },
  // EDGE CASE: Anonymous donation (no message)
  {
    id: "donation-15",
    donorId: "donor-5",
    crisisId: "crisis-1",
    amount: 100000,
    message: "",
    status: "completed",
    providerPreference: {
      positive: ["provider-1", "provider-3"],
      negative: [],
      geographicFocus: "Sylhet",
    },
    allocations: [
      {
        id: "alloc-15",
        donationId: "donation-15",
        beneficiaryId: "beneficiary-4",
        providerId: "provider-3",
        allocatedAmount: 100000,
        status: "completed",
        createdAt: "2024-06-09",
      },
    ],
    createdAt: "2024-06-08",
    refundSettings: {
      autoRefund: false,
    },
    transactionFee: 2500,
  },
]

// Mock Fraud Alerts for Admin Dashboard
export const mockFraudAlerts: FraudAlert[] = [
  {
    id: "fraud-1",
    type: "duplicate-nid",
    targetId: "beneficiary-suspicious-1",
    targetType: "beneficiary",
    severity: "high",
    description: "NID number 3333444455556 appears in 3 different applications within 7 days",
    evidence: [
      "Application from Dhaka on 2024-06-08",
      "Application from Sylhet on 2024-06-12",
      "Application from Khulna on 2024-06-14",
    ],
    status: "investigating",
    createdAt: "2024-06-14",
  },
  {
    id: "fraud-2",
    type: "cost-outlier",
    targetId: "provider-suspicious-1",
    targetType: "provider",
    severity: "medium",
    description: "Provider 'Quick Relief Org' requesting 65% above regional average for flood relief",
    evidence: [
      "Regional average: ৳3,200 per family",
      "Provider requesting: ৳5,280 per family",
      "Difference: 65% above average",
    ],
    status: "open",
    createdAt: "2024-06-13",
  },
  {
    id: "fraud-3",
    type: "gps-mismatch",
    targetId: "alloc-suspicious-1",
    targetType: "donation",
    severity: "critical",
    description: "Distribution photo GPS location 45km away from beneficiary stated address",
    evidence: [
      "Beneficiary address: Sylhet Sadar (24.89°N, 91.87°E)",
      "Photo GPS: Sunamganj (25.07°N, 91.39°E)",
      "Distance: 45.3 km",
    ],
    status: "open",
    createdAt: "2024-06-15",
  },
  {
    id: "fraud-4",
    type: "suspicious-pattern",
    targetId: "provider-suspicious-2",
    targetType: "provider",
    severity: "high",
    description: "Same 5 beneficiaries appearing in multiple provider applications",
    evidence: [
      "Beneficiary IDs: B-101, B-102, B-103, B-104, B-105",
      "Appeared in 4 different provider applications",
      "All applications within 10 days",
    ],
    status: "investigating",
    createdAt: "2024-06-12",
  },
  {
    id: "fraud-5",
    type: "deepfake",
    targetId: "alloc-suspicious-2",
    targetType: "donation",
    severity: "critical",
    description: "AI detected potential deepfake in distribution verification photo",
    evidence: [
      "Deepfake confidence: 87%",
      "Facial artifacts detected",
      "Lighting inconsistencies",
      "Metadata manipulation suspected",
    ],
    status: "open",
    createdAt: "2024-06-14",
  },
  {
    id: "fraud-6",
    type: "network-fraud",
    targetId: "fraud-ring-1",
    targetType: "provider",
    severity: "critical",
    description: "Network analysis shows 3 providers submitting same beneficiaries with different names",
    evidence: [
      "Same phone numbers across applications",
      "Same bank accounts",
      "Similar submission patterns",
      "Connected IP addresses",
    ],
    status: "investigating",
    createdAt: "2024-06-11",
  },
  // EDGE CASE: Low severity - minor documentation issues
  {
    id: "fraud-7",
    type: "duplicate-nid",
    targetId: "beneficiary-12",
    targetType: "beneficiary",
    severity: "low",
    description: "Possible NID number typo - similar to another application but likely data entry error",
    evidence: [
      "NID 9988776655443 vs previously registered 9988776655444",
      "Different names, addresses, and photos",
      "Likely human error in data entry",
    ],
    status: "resolved",
    createdAt: "2024-06-10",
  },
  // EDGE CASE: Provider under investigation for multiple issues
  {
    id: "fraud-8",
    type: "suspicious-pattern",
    targetId: "provider-2",
    targetType: "provider",
    severity: "medium",
    description: "Provider showing unusual rapid distribution pattern - completing 15 cases in 3 days",
    evidence: [
      "15 distributions completed Jun 12-15",
      "Average time: 4.8 hours per case (normal: 24-48 hours)",
      "All beneficiaries from same village",
      "Awaiting field verification",
    ],
    status: "investigating",
    createdAt: "2024-06-15",
  },
  // EDGE CASE: Resolved fraud case with explanation
  {
    id: "fraud-9",
    type: "gps-mismatch",
    targetId: "alloc-4",
    targetType: "donation",
    severity: "medium",
    description: "GPS coordinates 12km from stated address - RESOLVED: Beneficiary temporarily relocated",
    evidence: [
      "Original address: Village A",
      "Distribution location: Village B (12km away)",
      "Provider confirmed: Family temporarily staying with relatives",
      "Photo verification confirmed identity",
    ],
    status: "resolved",
    createdAt: "2024-06-09",
  },
  // EDGE CASE: Pending admin review
  {
    id: "fraud-10",
    type: "cost-outlier",
    targetId: "beneficiary-13",
    targetType: "beneficiary",
    severity: "low",
    description: "Requested amount 35% above average for food category - awaiting justification",
    evidence: [
      "Average food aid: ৳11,000",
      "Requested: ৳15,000",
      "Difference: 36% above average",
      "Large family size (9 members) may justify higher amount",
    ],
    status: "open",
    createdAt: "2024-06-12",
  },
]

// Mock Blacklist Entries
export const mockBlacklistEntries: BlacklistEntry[] = [
  {
    id: "blacklist-1",
    nid: "6666777788889",
    phone: "+88011XXXXXXXX",
    bankAccount: "XXX-YYYY-1234",
    email: "fraud@example.com",
    fraudType: "duplicate-applications",
    reason: "Applied 5 times with different names but same NID",
    evidence: ["Application screenshots", "NID verification mismatch", "Bank account linked to multiple identities"],
    addedDate: "2024-05-20",
    addedBy: "admin-1",
  },
  {
    id: "blacklist-2",
    nid: "9999000011112",
    phone: "+88010XXXXXXXX",
    fraudType: "fake-documents",
    reason: "Submitted forged NID and medical records",
    evidence: ["NIDW database mismatch", "Document metadata shows editing", "Hospital confirmed records are fake"],
    addedDate: "2024-06-01",
    addedBy: "admin-1",
  },
  {
    id: "blacklist-3",
    email: "scammer@fake.org",
    phone: "+88009XXXXXXXX",
    fraudType: "provider-fraud",
    reason: "Fake NGO registration, never distributed aid",
    evidence: [
      "NGO Bureau confirmed no such registration",
      "Beneficiaries never received aid",
      "Funds withdrawn but no distribution proof",
    ],
    addedDate: "2024-05-15",
    addedBy: "admin-2",
  },
  // EDGE CASE: Blacklisted for repeated application spam
  {
    id: "blacklist-4",
    nid: "4455667788990",
    phone: "+88007XXXXXXXX",
    email: "spammer@mail.com",
    fraudType: "duplicate-applications",
    reason: "Submitted 12 identical applications in 48 hours across multiple accounts",
    evidence: [
      "Same crisis photos used in all applications",
      "Identical text in descriptions (copy-pasted)",
      "Same device fingerprint detected",
      "IP address matched to VPN service",
    ],
    addedDate: "2024-06-05",
    addedBy: "admin-1",
  },
  // EDGE CASE: Provider blacklisted for fund misappropriation
  {
    id: "blacklist-5",
    email: "shadyorg@relief.org",
    phone: "+88006XXXXXXXX",
    fraudType: "provider-fraud",
    reason: "Received ৳250,000 in donations but distributed only ৳80,000 with no accounting",
    evidence: [
      "Bank statements show full withdrawal",
      "Only 8 of 25 claimed distributions verified",
      "Beneficiaries report receiving partial amounts",
      "No response to admin inquiries for 30 days",
    ],
    addedDate: "2024-05-28",
    addedBy: "admin-2",
  },
  // EDGE CASE: Temporary blacklist - under investigation
  {
    id: "blacklist-6",
    phone: "+88005XXXXXXXX",
    fraudType: "suspicious-pattern",
    reason: "TEMPORARY: Multiple failed verification attempts - investigating potential account compromise",
    evidence: [
      "5 login attempts from different countries in 2 hours",
      "Password reset requested 8 times",
      "Unusual application pattern detected",
      "Account frozen pending identity verification",
    ],
    addedDate: "2024-06-14",
    addedBy: "admin-1",
  },
]

// Mock Distribution Proofs for Completed Allocations
export const mockDistributionProofs: DistributionProof[] = [
  {
    id: "proof-1",
    allocationId: "alloc-1",
    preSiteVisitPhotos: ["/pre-visit-1.jpg", "/pre-visit-2.jpg"],
    beneficiaryConsentForm: true,
    distributionPhotos: ["/distribution-1.jpg", "/distribution-2.jpg"],
    distributionVideos: ["/distribution-video-1.mp4"],
    itemsVerified: [
      { item: "Corrugated tin sheets", quantity: 20 },
      { item: "Wood and bamboo", quantity: 50 },
      { item: "Nails and cement", quantity: 1 },
    ],
    beneficiarySignature: "/signature-1.jpg",
    postDistributionPhotos: ["/post-dist-1.jpg", "/post-dist-2.jpg"],
    receiptImages: ["/receipt-1.jpg"],
    beneficiaryConfirmationSMS: true,
    gpsCoordinates: { lat: 22.35, lng: 89.08 },
    timestamp: "2024-06-12T10:30:00Z",
    distributionDate: "2024-06-12",
    deepfakeDetection: true,
    faceMatchScore: 96,
    gpsValidation: true,
    imageQualityScore: 92,
    verificationStatus: "verified",
  },
  {
    id: "proof-2",
    allocationId: "alloc-4",
    preSiteVisitPhotos: ["/pre-visit-3.jpg"],
    beneficiaryConsentForm: true,
    distributionPhotos: ["/distribution-3.jpg", "/distribution-4.jpg"],
    distributionVideos: [],
    itemsVerified: [
      { item: "Fishing nets", quantity: 2 },
      { item: "Boat repair materials", quantity: 1 },
      { item: "Fishing equipment", quantity: 5 },
    ],
    beneficiarySignature: "/signature-2.jpg",
    postDistributionPhotos: ["/post-dist-3.jpg"],
    receiptImages: ["/receipt-2.jpg"],
    beneficiaryConfirmationSMS: true,
    gpsCoordinates: { lat: 25.07, lng: 91.39 },
    timestamp: "2024-06-14T14:15:00Z",
    distributionDate: "2024-06-14",
    deepfakeDetection: true,
    faceMatchScore: 94,
    gpsValidation: true,
    imageQualityScore: 88,
    verificationStatus: "verified",
  },
  {
    id: "proof-3",
    allocationId: "alloc-7",
    preSiteVisitPhotos: ["/pre-visit-4.jpg", "/pre-visit-5.jpg"],
    beneficiaryConsentForm: true,
    distributionPhotos: ["/distribution-5.jpg"],
    distributionVideos: ["/distribution-video-2.mp4"],
    itemsVerified: [
      { item: "Corrugated tin sheets", quantity: 15 },
      { item: "Wood and bamboo", quantity: 40 },
      { item: "Nails and cement", quantity: 1 },
    ],
    beneficiarySignature: "/signature-3.jpg",
    postDistributionPhotos: ["/post-dist-4.jpg", "/post-dist-5.jpg"],
    receiptImages: ["/receipt-3.jpg"],
    bankTransferScreenshots: ["/bank-transfer-1.jpg"],
    beneficiaryConfirmationSMS: true,
    gpsCoordinates: { lat: 22.35, lng: 89.08 },
    timestamp: "2024-06-12T09:45:00Z",
    distributionDate: "2024-06-12",
    deepfakeDetection: true,
    faceMatchScore: 98,
    gpsValidation: true,
    imageQualityScore: 95,
    verificationStatus: "verified",
  },
  // EDGE CASE: Proof pending review - incomplete documentation
  {
    id: "proof-4",
    allocationId: "alloc-12a",
    preSiteVisitPhotos: ["/pre-visit-6.jpg"],
    beneficiaryConsentForm: true,
    distributionPhotos: ["/distribution-6.jpg"],
    distributionVideos: [],
    itemsVerified: [
      { item: "Tin sheets", quantity: 15 },
      { item: "Construction materials", quantity: 1 },
    ],
    beneficiarySignature: "/signature-4.jpg",
    postDistributionPhotos: [],
    receiptImages: ["/receipt-4.jpg"],
    beneficiaryConfirmationSMS: false,
    gpsCoordinates: { lat: 22.87, lng: 91.1 },
    timestamp: "2024-06-10T11:20:00Z",
    distributionDate: "2024-06-10",
    deepfakeDetection: true,
    faceMatchScore: 91,
    gpsValidation: true,
    imageQualityScore: 78,
    verificationStatus: "pending",
  },
  // EDGE CASE: Proof with warnings - low face match score
  {
    id: "proof-5",
    allocationId: "alloc-12b",
    preSiteVisitPhotos: ["/pre-visit-7.jpg"],
    beneficiaryConsentForm: true,
    distributionPhotos: ["/distribution-7.jpg", "/distribution-8.jpg"],
    distributionVideos: [],
    itemsVerified: [
      { item: "Emergency shelter materials", quantity: 1 },
    ],
    beneficiarySignature: "/signature-5.jpg",
    postDistributionPhotos: ["/post-dist-6.jpg"],
    receiptImages: ["/receipt-5.jpg"],
    beneficiaryConfirmationSMS: true,
    gpsCoordinates: { lat: 22.87, lng: 91.11 },
    timestamp: "2024-06-12T15:30:00Z",
    distributionDate: "2024-06-12",
    deepfakeDetection: true,
    faceMatchScore: 72,
    gpsValidation: true,
    imageQualityScore: 85,
    verificationStatus: "pending",
  },
  // EDGE CASE: Rejected proof - GPS mismatch
  {
    id: "proof-6",
    allocationId: "alloc-suspicious-1",
    preSiteVisitPhotos: ["/pre-visit-suspicious.jpg"],
    beneficiaryConsentForm: true,
    distributionPhotos: ["/distribution-suspicious.jpg"],
    distributionVideos: [],
    itemsVerified: [
      { item: "Fire relief materials", quantity: 1 },
    ],
    beneficiarySignature: "/signature-suspicious.jpg",
    postDistributionPhotos: [],
    receiptImages: [],
    beneficiaryConfirmationSMS: false,
    gpsCoordinates: { lat: 23.79, lng: 90.41 },
    timestamp: "2024-06-15T16:45:00Z",
    distributionDate: "2024-06-15",
    deepfakeDetection: false,
    faceMatchScore: 65,
    gpsValidation: false,
    imageQualityScore: 62,
    verificationStatus: "flagged",
  },
  // EDGE CASE: Excellent proof with all optional fields
  {
    id: "proof-7",
    allocationId: "alloc-15",
    preSiteVisitPhotos: ["/pre-visit-8.jpg", "/pre-visit-9.jpg", "/pre-visit-10.jpg"],
    beneficiaryConsentForm: true,
    distributionPhotos: ["/distribution-9.jpg", "/distribution-10.jpg", "/distribution-11.jpg"],
    distributionVideos: ["/distribution-video-3.mp4", "/distribution-video-4.mp4"],
    itemsVerified: [
      { item: "Complete flood relief package", quantity: 1 },
      { item: "Food supplies", quantity: 1 },
      { item: "Medical supplies", quantity: 1 },
    ],
    beneficiarySignature: "/signature-6.jpg",
    postDistributionPhotos: ["/post-dist-7.jpg", "/post-dist-8.jpg", "/post-dist-9.jpg"],
    receiptImages: ["/receipt-6.jpg"],
    bankTransferScreenshots: ["/bank-transfer-2.jpg"],
    beneficiaryConfirmationSMS: true,
    gpsCoordinates: { lat: 25.07, lng: 91.39 },
    timestamp: "2024-06-09T10:00:00Z",
    distributionDate: "2024-06-09",
    deepfakeDetection: true,
    faceMatchScore: 99,
    gpsValidation: true,
    imageQualityScore: 98,
    verificationStatus: "verified",
  },
]
